- package.json
- src/api/index.ts
- src/app/store.ts
- src/date/index.ts
- src/deploy/app/index.ts
- src/deploy/code-scan-result/index.ts
- src/deploy/database-images/index.ts
- src/deploy/database/index.ts
- src/deploy/operation/index.ts
- src/deploy/state.ts
- src/hal/index.test.ts
- src/hal/index.ts
- src/projects/index.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/pages/create-project-git.tsx
- yarn.lock
This commit also:
- Displays results of code scan on the create git settings page
- Save all operations inside redux as its own separate entity (as opposed to using auto-caching)
- And create selectors to pull data from that redux slice
- Created a discriminated union for the `createAppOperation` endpoint
- Adds `app:deploy` as an operation for `createAppOperation`
- Uses `app:deploy` inside `deployProject`
> Code scanning

- package.json
- src/api/index.ts
- src/deploy/operation/index.ts
- yarn.lock
The `fetchRetry` middleware from `saga-query` accesses the actual fetch request and will keep calling it multiple times until there is a success.
You can read more here: https://github.com/redux-saga/saga-query/releases/tag/v7.2.0
> chore(ftux): use saga-query fetchRetry middleware

- src/app/store.ts
Leaving as draft. This should have no impact (or nearly no impact). There are all sorts of blog posts and stuff about customizing this thing for prod: https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f, but I think we can really just use this and there's some primitive settings we can use to disable in prod if you wish.
Similarly we're using a deprecated method, which I'm trying to solve here:
---
Proof:
Pretty handy dandy to view state:
> chore: added redux dev tools extension optionally

- src/app/router.tsx
- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/projects/index.ts
- src/routes/index.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/detail-page.tsx
- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/breadcrumbs.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/index.ts
- src/ui/shared/pre-code.tsx
- src/ui/shared/tabs.tsx
- src/ui/shared/tokens.ts
- tailwind.config.cjs
* This adds a common component that is sort-of reused in both app/database pages
* This allows for deprovisioning of an app/database (and it looks to work!, though I need to check with Josh on some of it as some operations failed with rollback failed)
* Cleans up some tab behavior (I will likely need to talk to you about this Eric as this alters the index behavior)
Edit - can update to include screenshots but I think e2e testing or something deprovisioned my testing stack and I'll probably test against it in the morn for a fresh batch. It looks pretty close to the current mocks though! (Screenshot a bit below but that's slightly outdated)
app management:
db management:
> feat: added settings/deprovision page for apps

- src/env/index.ts
- src/types/state.ts
- src/ui/pages/create-project-git.tsx
- src/vite.d.ts
We already have an `origin` that we use to send to `auth-api` in order to determine which app the email verification links should redirect to so we can reuse that for determining if we are using the full-blown app or ftux.
> chore: ability to determine which app is running (ftux or nextgen)

- .env.example
- .github/workflows/deploy.yml
- .github/workflows/staging.yml
- Dockerfile
- README.md
- package.json
- src/app/app.tsx
- src/app/init.ts
- src/app/sentry.ts
- src/app/store.ts
- src/env/index.ts
- src/types/state.ts
- src/ui/shared/error-boundary.tsx
- src/vite.d.ts
- yarn.lock
There is one outstanding issue for us to review:
---
can see them in sentry itself:
saga-query error forced (note log):
> sc-11529 - sentry addition

- src/api/index.ts
- src/app/app.tsx
- src/app/router.tsx
- src/ui/index.ts
- src/ui/shared/error-boundary.tsx
- src/ui/shared/index.ts
It works for simulated errors (not shown, but reports to sentry):
It renders:
It does properly send on boundary:
> fix: corrected error boundary behavior for common cases

- src/types/state.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/onboarding-link.tsx
The value of `origin` is important to `auth-api` so we want it to be the "final" value so we don't have to change it after the initial implementation.
Related: https://github.com/aptible/auth-api/pull/500
> fix(ftux): origin can only be `nextgen` or `app`

- src/api/index.ts
- src/auth/token.ts
We were always sending `localStorage.token` to `/current_token` and `auth-api` would return that token ... even if the `session_token` had a more recent one.
This ensures we never send `/current_token` the token stored in local storage.
- [current_token_id](https://github.com/aptible/auth-api/blob/c26e460bd13d7f1d9ab8f814d50ee4d772305512/app/controllers/application_controller.rb#L10)
- [current_token](https://github.com/aptible/fridge/blob/38fadfb6b515fdf29d8e537412a8a32424bedddd/lib/fridge/rails_helpers.rb#L22)
- [session_token](https://github.com/aptible/fridge/blob/38fadfb6b515fdf29d8e537412a8a32424bedddd/lib/fridge/rails_helpers.rb#L43)
> fix: dont send local storage token to /current_token

- src/projects/index.ts
- src/ui/pages/create-project-git.tsx
I discovered a bug where sometimes we wouldn't try to deploy the App from the settings page.
I also removed some assumptions about existing databases that was janky and error-prone.
I also made it so a user cannot see endpoint until vhost provision completes.
> fix(ftux): settings page should always try to deploy an app

- src/deploy/app/index.ts
- src/deploy/environment/index.ts
- src/deploy/operation/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/onboarding-link.tsx
Fixes:
- Deployments page now has same status pill as status page
- Deployments page now has correct "finish setup" link
- Deployments are listed by `App` instead of `Account`
- If there are 0 operations for an `Account` we resolve that status to `unknown` instead of `succeeded`
> ftux deployments by app

- src/ui/shared/cookie-notice.tsx
Caught as the production cookie doesn't read off `.aptible.com`, but rather `app.aptible.com`:
---
This should work in all situations without errors
including invalid domains
or other setups
> chore: updated cookie consent to work regardless of subdomain

- src/app/app.tsx
- src/app/router.tsx
- src/app/tuna.tsx
This apparently doesn't change on dom router changes (which makes sense). 
We either need to introduce a shared layout or use a patch on every top level item in the router (I found that less intrusive)
---
Error component retained:
---
on two navs:
> fix: added tuna patch for router loc changes

- package.json
- src/test/setup.ts
- yarn.lock
See: https://testing-library.com/docs/react-testing-library/api/#cleanup
> fix: `afterEach` cleanup for `@testing-library`

- src/app/router.tsx
- src/auth/verify-email.ts
- src/mocks/handlers.ts
- src/test/index.tsx
- src/ui/hooks/use-verified-required.ts
- src/ui/layouts/auth-required.test.tsx
- src/ui/layouts/auth-required.tsx
- src/ui/pages/verify-email.test.tsx
- src/ui/pages/verify-email.tsx
- src/ui/shared/verify-email/resend-verification-email-form.tsx
Fairly tedious, tested that when nextgen is enabled someone remains in nextgen without exiting.
Tested these flows on the email verification page (has 3 possible flows - tested manually, needing to write automated tests):
* email verification button clicked
* arrives with url params (should post and verify -> go home)
* already verified, redirect home
Tested these flows on the home page:
* Login
* Forced takeover of email verify
* Allow logout
sc-14708
---
Logout changes and ability to logout on :
> chore: minor tests/fixes for email verification and end to end tests

- src/mocks/handlers.ts
- src/ui/hooks/use-verified-required.ts
- src/ui/layouts/auth-required.test.tsx
Caught on nextgen-sbx-main.
If you go to a page and reload with a verified email, you will get punted to root as the current user won't be loaded in time. Using this ensures that the user is always loaded on boot.
Verified in local and updated unit tests.
> chore: updated use verified required which is glitchy as heck on pagereload without this change

- src/deploy/code-scan-result/index.ts
- src/ui/pages/create-project-git.tsx
If codescan result is python, we show the following for users that might run into common python issues with builder:
---
QA on view Dockerfile if avail
• Banner
• Toggle Control Label (Hide Dockerfile | Show Dockerfile)
• Code Snippet
• Divider line
> chore: more granular error messages 

- src/app/packages.ts
- src/auth/index.ts
- src/auth/roles.ts
- src/deploy/environment/index.ts
- src/deploy/index.ts
- src/deploy/permission/index.ts
- src/deploy/permission/selectors.test.ts
- src/deploy/state.ts
- src/initial-data/index.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/roles/index.ts
- src/test/setup.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-perm-required.ts
- src/ui/layouts/index.ts
- src/ui/layouts/perm-required.tsx
- src/ui/pages/perms.test.tsx
- src/ui/shared/button.tsx
- src/ui/shared/index.ts
- src/ui/shared/permission.tsx
Adds the following functions to be used in our app:
- `selectUserHasPerms` (permission business logic)
- `usePermsRequired` (redirects if user doesn't have perms)
- `PermissionGate` (return `null` if user doesn't have perms)
- `PermRequired` (layout that redirects if user doesn't have perms)
- `createButtonPermission` (button generator for perms)
- `ButtonCreate` (disables button if user doesn't have ability to create resources)
- `ButtonDestroy` (disables button if user doesn't have ability to destroy resources)
> permissions ui

- src/deploy/operation/index.ts
- src/types/deploy.ts
- src/ui/layouts/op-detail-layout.tsx
- src/ui/shared/activity.tsx
- add operation note to activity page and detail page
- add operation id to type
https://app.shortcut.com/aptible/story/14841/display-the-operation-note-field-in-resource-activity-views-when-populated
> add operation note into activity and detail page, add id to type

- src/ui/shared/application-sidebar.tsx
- src/ui/shared/org-picker.tsx
• Tighten Org Chooser Spacing
• Made Org Chooser the same width as our selected nav items
BEFORE
AFTER
> tighten-org-chooser-spacing-jc

- src/ui/shared/application-sidebar.tsx
Make Install CLI link go to the proper page — https://www.aptible.com/docs/cli
Before it went to a 404
> Fix Broken Link

- src/ui/shared/active-operation-notice.tsx
- src/ui/shared/op-status.tsx
Make Banner Margin-Bottom Only
**Before**
**After**
Make Queued Status text color a bit darker
**Before**
**After**
> Banner Margin Tweak and Darken Queued Status

- src/ui/pages/elevate.tsx
- src/ui/pages/forgot-pass.tsx
- src/ui/pages/login.tsx
- src/ui/pages/signup.tsx
- src/ui/pages/verify-email.tsx
Add border to all onboarding container boxes
• Slight margin & padding tweaks to save some space
**BEFORE**
**AFTER**
Add more margin above box to be consistent
Add border to box
Add border to box
> Add-Border-to-Onboarding-Boxes-jc

- src/ui/pages/stacks.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/tooltip.tsx
Add top level page tooltips for Stacks, Environments, Apps, Databases, and Activity pages.
https://github.com/aptible/app-ui/assets/4295811/0ef4b447-3c70-45e6-8ac3-c2d871900027
> top-level-tooltips-jc

- src/deploy/container/index.ts
- src/ui/pages/app-detail-service.tsx
this fixes by only filtering on apps and database layers' containers
proof provided in slack thread
> chore: filtered metrics by more args

- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/container-metrics-table.tsx
Make metrics table responsive
BEFORE
• Does NOT scroll horizontally
AFTER
• Scrolls horizontally
• Cells are easier to read
• Add TROW hover state to boost legibility in sea of data
> Make Metrics Table Responsive

- src/ui/pages/create-project-git.tsx
Add missing margin to FTUX only for users coming from deploy-ui
BEFORE
AFTER
> Fix-Margin-Bug-jc

- src/app/router.tsx
- src/ui/pages/login.tsx
**Quickfix so we don't have to spend more time on Sign Up flow bugs** 
• On the Login Page, point the sign up link to https://dashboard.aptible.com/signup
> Change-Login-Link-jc

- index.css
- src/date/index.ts
- src/ui/pages/stacks.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/date-text.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/tooltip.tsx
- yarn.lock
Full format (in UTC):
Example tooltip:
---
We can use these as needed in various places
> chore: added date formats for reuse

- src/app/router.tsx
- src/deploy/environment/index.ts
- src/deploy/index.ts
- src/deploy/state.ts
- src/deploy/vpc_peer/index.ts
- src/deploy/vpn_tunnel/index.ts
- src/hal/index.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/pages/index.ts
- src/ui/pages/logout.test.tsx
- src/ui/pages/stack-detail-environments.tsx
- src/ui/pages/stack-detail-vpc-peering.tsx
- src/ui/pages/stack-detail-vpn-tunnels.tsx
- src/ui/pages/stack-detail.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/environment/environment-list.tsx
Fairly straightforward:
* stack detail environment list
* stack detail vpn tunnels
* stack detail vpc peers
basically ports current screens where possible:
vpn tunnels
vpc peers
stack detail w/ env list:
> feat: added stack pages

- src/ui/shared/activity.tsx
Properly Float Logs button right
BEFORE
AFTER
> Float Logs Button Right

- src/ui/shared/footer.tsx
Hide legacy view and changelog links on mobile
> footer-mobile-tweaks-jc

- src/ui/shared/app/services-detail.tsx
Right align metrics button on services table
BEFORE
AFTER
> Right align metrics button on services table

- nginx.conf
do not cache index.html (but leave everything else as is) so we don't flash white pages when we have newer deploys
running in locally built docker image:
> chore: do not cache index.html to force reload

- src/metric-tunnel/index.ts
- src/ui/shared/container-metrics-chart.tsx
- src/ui/shared/container-metrics-table.tsx
* multicontainer support
* timestamps in tooltips
---
multiple containers should appear properly now:
timestamp on tooltips:
> chore: updated multi-container reporting on charts

- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/shared/application-sidebar.tsx
Fix padding issues so icons are aligned properly to the bar's width.
BEFORE & AFTER
> Collapsed Navigation Styling

- src/metric-tunnel/index.ts
- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
> chore: use client caching + limit number of requests in loops

- src/date/index.ts
- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/metrics-controls.tsx
Correctly results in zero or near zero 404s from metrictunnel service now
No failures in PR:
Ex equiv in prod:
> fix: dropped excessive calls that should not get hit (before metrichorizon OR current)

- src/metric-tunnel/index.ts
- src/ui/shared/container-metrics-chart.tsx
> chore: added fix for using proper unit on chartjs x cartesian scale config

- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/container-metrics-chart.tsx
- src/ui/shared/tooltip.tsx
I dropped his refresh for now because we don't allow per-chart refreshes (but it's automated on page load for now) and not on-demand, though we can come back to this at some point
I also added some right alignment to tooltips optionally for things that are right aligned (so they don't fall off the edge of the screen):
> fix: QA feedback from bulk of Joe's changes

- src/ui/shared/container-metrics-chart.tsx
> fix: incorrectly dropped chartjs tooltips in favor of aptible ones, but need both

- src/ui/pages/environment-detail-certificates.tsx
Make certificates status pills flex-row to fit more above the fold & save space.
Before
After
> Make certificates status pills flex row

- src/ui/layouts/error-boundary.tsx
- src/ui/pages/elevate.tsx
- src/ui/pages/login.tsx
- src/ui/pages/signup.tsx
- src/ui/shared/box.tsx
On mobile screens, login, sign up, 404 page buttons and input fields lose all their padding around them (the container div padding drops). This fixes that.
BEFORE
AFTER
> Fix mobile login box styling

- src/ui/shared/box.tsx
Correct shared box padding size
BEFORE - too big
AFTER
> Fix-Shared-Box-Padding

- src/ui/shared/plan.tsx
Update Plans Page
I can't fix this bug though:
These 2 lines of code are preventing the page from displaying at 100% width properly. They live on the hero-bg file instead of the plans file. I dont wanna mess up any of the existing hero-bg pages (FTUX).
`<div style="width: 1200px;">`
`<div class "flex justifv-center container">`
Here's the desired end state
> Update Plans page

- src/ui/layouts/app-detail-layout.tsx
Remove the word deploy and just show the date for Last Deployed info inside the header card.
BEFORE - We don't need say the word Deploy again below the Last Deployed Header
AFTER
> Simplify-App-Header-Card

- src/ui/shared/pre-code.tsx
In deploy-ui, the current behavior is to wrap code. This PR matches that behavior.
BEFORE
AFTER
> Fix Code Wrapping Bug

- src/ui/shared/table.tsx
Allow long TDs to wrap in our tables
BEFORE - TD content overflows
AFTER
> Table Tweaks

- src/deploy/app/utils.ts
This was coercing a 0.25 multiplier every time, which was wrong. It needed to use the cpushare for the instance class to work
---
With fix
matches prod
---
Without fix (note it's 1, not 0.5):
> chore: corrected some numbers on tables/layout views

- src/ui/pages/db-detail-backups.tsx
- src/ui/pages/environment-detail-backups.test.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/environment/backup-retention-policy-view.tsx
- src/ui/shared/icons.tsx
Add Edit Backup Policy Button to "Database / Backups Tab"
When clicked the button navigates to it's parent environment's backups tab.
Edit Backup Policy Button
Link destination
> Add-EditBackupPolicyButton

- src/ui/shared/container-metrics-table.tsx
Adding a non-mobile breakpoint for w-full to the metrics table. This bug only happens when the sidebar is toggled open.
BEFORE - View of my viewport on the right side
AFTER - View of my viewport on the right side
> Fix-Metrics-Table-Overflow

- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/db-detail-settings.tsx
Move Reveal Credentials to Database Header
BEFORE
AFTER
> move-reveal-creds-to-db-header

- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/environment/environment-list.tsx
Keep our page headers spacing consistent so the search bar (ex. Search Environments) doesn't shift between pages
https://github.com/aptible/app-ui/assets/4295811/b7c9348c-a923-4bf0-9e5f-417fe055ab4c
and
Small copy tweak for empty endpoint page
> Keep Header Spacing Consistent

- src/ui/pages/org-picker.tsx
- src/ui/shared/org-picker.tsx
• Add hover state to org picker button
• Made "Choose Organization" type match the same font-size as our page labels (h2)
BEFORE
AFTER
> Org Picker Button Styling

- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/log-drain/index.ts
- src/deploy/metric-drain/index.ts
- src/types/deploy.ts
- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-integrations.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/button.tsx
- src/ui/shared/group.tsx
- src/ui/shared/index.ts
- src/ui/shared/input.tsx
~TODO - disable on v4 log drains as well (restart not allowed)~
---
* ~proof~
* ~tests~ (adding to part 2 with deletes)
delete works w/ confirm
if v4, would look like this:
> chore: added restart actions for dbs/apps/drains

- src/ui/shared/input.tsx
**Fix search icon alignment**
BEFORE
AFTER
> fix-search-icon-aligment

- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/pages/search.tsx
Tighten Page Margins
• Make page headers a bit tighter so they align better optically
• Make the search page tighter
> Tighten-Page-Margins-Optically

- src/deploy/container/utils.ts
Ports a change from https://github.com/aptible/deploy-ui/pull/770 over to app-ui: update the max container size for m5 to 376,832 MB to match the maximum possible currently allowed by [deploy-api](https://github.com/aptible/deploy-api/blob/master/app/models/container.rb#L145) and [sweetness](https://github.com/aptible/sweetness/blob/master/lib/sweetness/constants.rb#L53).
m5 is not currently enabled in app-ui so this change should have no effect until it's enabled in a follow-up PR.
> Increase m5 max container size to match deploy-api limits

- src/ui/pages/environment-detail-integrations.tsx
Right align actions for Log Drains and Metric Drains
BEFORE
AFTER
> Right-Align-Actions-for-LogDrains-and-MetricDrains

- src/ui/pages/create-log-drain.tsx
Fix Log Drain Typo, LogDNA is now called Mezmo
BEFORE
AFTER - Mezmo is the correct label
> fix-logdrain-typo

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/cert-detail-settings.tsx
- src/ui/pages/db-detail-creds.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/endpoint/util.tsx
**Text Change**
BEFORE
AFTER
**Unify Deprovision Header Styles**
BEFORE - Alert icon was different sizes on different deprovision boxes
AFTER
> designs-tweaks-jc

- src/ui/pages/create-project-git.tsx
- src/ui/shared/select.tsx
Changes
• Added explainer text "Launch your existing app with Custom Code, or learn how Aptible works with a Starter Template."
• Added the word Template after each starter template in the dropdown to reinforce what it is to users
---
**Dropdowns**
• Don't Lighten Label Text color on hover
• Only darken the border-color
BEFORE
AFTER
> Push-Code-Step-Tweaks

- src/ui/shared/environment/environment-activity-report-list.tsx
Make it clear that downloads are CSV files & make hit area larger
BEFORE
AFTER
> download-button-tweak

- src/deploy/endpoint/index.ts
> fix(enp): only provide `enp.certificate` if there is a certId

- src/api/index.ts
- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/deploy/environment/index.ts
- src/deploy/log-drain/index.ts
- src/deploy/metric-drain/index.ts
- src/deploy/service/index.ts
- src/deploy/stack/index.ts
- src/initial-data/index.ts
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/create-project-name.tsx
- src/ui/pages/deployments.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/select-environments.tsx
- src/ui/shared/select-stacks.tsx
This PR cleans up some of our old logic for fetching index pages now that we can fetch all resources in a single request.  It further adds a modest cache timer (60 seconds) so we don't keep fetching index pages when we just fetched them successfully.
> Fetch cache requests

- src/ui/layouts/hero-bg-layout.tsx
Center Divs
• Stop jumping on breakpoints
BEFORE
https://github.com/aptible/app-ui/assets/4295811/045fce06-517b-4ab1-96f6-bb3c65f0e41c
AFTER
https://github.com/aptible/app-ui/assets/4295811/3363c90c-ff85-47b2-b105-2b7ef86b8c09
> improve-div-centering-on-mobile-breakpoints

- src/auth/login.ts
Whenever we receive a 401 unauthorized we reset the user's token.  Well that's the status code we receive when trying to automatically elevate a token with otp/u2f, probably because those code have already been used.
> fix(login): dont auto elevate token if u2f or otp present

- src/app/test/create-project.test.tsx
- src/mocks/data.ts
- src/redirect-path/index.ts
- src/routes/index.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-ssh-key-required.ts
- src/ui/layouts/auth-required.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/signup.tsx
- src/ui/shared/add-ssh-key.tsx
The big change here is to look for SSH keys on the git push page -- which is the only page that actually requires it an SSH key.
> Require ssh key ftux sc 18229

- src/ui/shared/application-sidebar.tsx
Make Support link easier to click
BEFORE
AFTER
> support-link-tweaks

- src/api/index.ts
Impacted users:
- Users with OTP; and
- Users without SSH keys
This regression was caused by us trying to fix:
- User goes to app logged in via cookie
- User's token expired while still using app
- User should get sent to `/login` page
Unfortunately this caused an issue for users with OTP trying to elevate their token.  When we try to `POST /tokens` with no otp token the API responds with a `401` which is what we use to determine if the token is not longer valid.
This was not an issue when a user logging in for the first time because they are already on the `/login` page.
Current solution is to only redirect to login when a `GET` request returns a `401`.
> fix(elevate): infinite loop

- src/app/test/app-detail-service-scale.test.tsx
- src/app/test/db-detail-scale.test.tsx
- src/mocks/handlers.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-scale.tsx
- src/ui/pages/db-detail-settings.tsx
When a user creates operations we sometimes don't have a good place to send them so we redirect to the operation detail page.
This is fine but not great.  We have some better places to send the user now -- mostly resource detail activity tabs.
> refactor(ops): redirect to more relevant pages

- src/ui/shared/environment/environment-activity-report-list.tsx
Simplify Activity Reports date format
AFTER:
> fix(app): change activity report date format

- src/ui/shared/environment/backup-retention-policy-view.tsx
Remove Cancel Button on Backup Retention Policy Form
BEFORE
AFTER
> fix(app):remove cancel button on backup retention policy form

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/stack-detail-vpc-peering.tsx
- src/ui/pages/stack-detail-vpn-tunnels.tsx
Tighten spacing on How to Deploy Changes block
BEFORE
AFTER
> style(app): tighten spacing on how to deploy changes box

- .github/workflows/deploy.yml
- Dockerfile
https://aptible.slack.com/archives/C022BUSF0B1/p1696008899449919
> 'Stripe::InvalidRequestError: No such token: 'xxx'; a similar object exists in test mode, but a live mode key was used to make this request.'
> fix(credit-card): use production stripe key for prod build

- src/ui/pages/create-stack.tsx
So we want to allow those users to request a dedicated stack
https://aptible.slack.com/archives/C022BUSK487/p1696265649228749
> fix(stack): empty active plan means legacy enterprise

- src/ui/shared/input.tsx
Changes
• Currently checkbox click targets span beyond the label text length into empty whitespace
• This change makes only the checkbox + the label text clickable to prevent accidental clicks
BEFORE
https://github.com/aptible/app-ui/assets/4295811/3e02c341-0868-4b6d-bdf1-1f2c6000456a
AFTER
https://github.com/aptible/app-ui/assets/4295811/e6dc1595-7c42-4ce2-a0d6-e223e8f285e1
> style: make checkbox click targets fit their content width

- src/ui/pages/create-project-git.tsx
Update deployment failed instructions to be more clear
BEFORE
AFTER
> style: deployment failed text

- vite.config.mjs
It's unclear why so I just added a notice to make it clear to never include it in our vendor bundle.
We might want to investigate a different library for our date formatting
> fix: including `date-fns` into our vendor bundle breaks the app

- src/ui/shared/app/services-detail.tsx
No need to show service type 2x
BEFORE
AFTER
> fix: remove duplicate of service type

- src/ui/shared/active-operation-notice.tsx
Capitalize first letter in operation banners
BEFORE
AFTER
> fix: capitalize operation banners

- src/app/router.tsx
- User is using the app
- We deploy a new ui release
- User navigates to a page that was lazy loaded (any page with charts)
- The lazy loaded that was for their current running app has disappeared
- User gets an error
- https://aptible.sentry.io/issues/4396767688/?project=4504990894391296&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0
- https://aptible.sentry.io/issues/4536245328/?project=4504990894391296&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=5
> refactor(chart): remove lazy loading

- src/ui/shared/detail-page-header-view.tsx
Make sure header items break on small screens
BEFORE
AFTER
> style: add break-all to header info items

- src/app/store.ts
- src/ui/layouts/auth-required.tsx
Storing the token is wrought with edge cases.  This commit fixes the current erroneous user flow:
- User has app and dashboard open using the same token
- In dashboard, user deletes the token (by logging out)
- In dashboard, user logs in again (creating new token)
- In app, user refreshes
- EXPECTED: user fetches `/current_token` and is allowed in app
- ACTUAL: user is redirected to login page
This erroneous behavior is caused by us trying to use the expired token stored in local storage -- even before we hit `/current_token`.  Since we used the wrong token the API would return a 401 and we would immediately wipe the redux store which would then send the user to the login page.  This would all happen before `/current_token` had a chance to provide us with the new valid token.
Because we …
> fix(token): dont keep token in local storage

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/cert-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/op-detail-layout.tsx
- src/ui/pages/search.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/stack.tsx
Resize icons to fit the space better & match design
• change doesn't increase table row height too
BEFORE
AFTER
BEFORE
AFTER
> style: resize icons

- src/ui/shared/activity.tsx
Fix logs button align on activity table
BEFORE
AFTER
> fix: logs button alignment

- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/service/index.ts
- src/ui/shared/activity.tsx
Had a bug (https://aptible.zendesk.com/agent/tickets/49443) where the App's activity page would not show the services activity as well ie the scale operations from the service.
- Refactor `ActivityByApp` to include the App's services as well.
> refactor selectActivityByApp to include services

- src/ui/shared/app/services-detail.tsx
Center the **No Resources Found** text inside empty Services tables
BEFORE
AFTER
> style: service table empty colspan

- src/ui/pages/billing-method.tsx
- src/ui/shared/how-it-works-footer.tsx
**Add more context to How It Works section to make it clear clicking Get Started guides users through steps.**
• We only show this on the `/create` pages now 
---
**Update Billing page to match the new sign up messaging**
> fix: update billing page and how it works copy

- src/ui/pages/deployments.tsx
Add title bar to Deployments page to match other pages
> fix: add title bar to deployments

- src/app/test/create-db.test.tsx
- src/deploy/database/index.ts
When a user tries to create and provision a new database we first perform a check to see if a database with that exact name already exists within the system.  If it does already exist, we skip creating the database and instead move onto provision the database.
We do this because there are cases where a user can create a database but the provision operation fails (e.g. user hits plan limits).  When the user fixes the issue and returns to FTUX to try to reprovision, we would then say validation failed because the database already exists.  So if that database already exists we just try to reprovision.
Creating a database record and provisioning that database are two separate, atomic events.  Coordinating those events rests solely on the UI.  Users can create as many database records as they …
> fix(db.create): look for existing db only in selected env

- src/ui/pages/stack-detail-hids.tsx
- src/ui/shared/table.tsx
Make all buttons with Td variant="right" show on the right always
BEFORE
AFTER
> fix: action button placement

- src/ui/pages/op-detail.tsx
The poller was causing the log viewer to be re-rendered everytime we fetched the operation.  When the operation is in a final state, we don't need to keep fetching it, so I removed the poller in those cases.
> fix(op): users should be able to select operation logs

- src/ui/pages/billing-method.tsx
- src/ui/pages/plans.tsx
- src/ui/pages/signup.tsx
**Changes**
• Make sidebar panel width match on Signup & Billing pages & reduce padding so its less tall
• Make sidebar always reach the bottom of viewports
• Make the Org Picker show in the form, so its super clear its for choosing an org
• Make the Org Picker have a min-width so it looks more clickable
• Reduced padding-top above the Get Started for Free headline to make the page less tall
**BEFORE — Bottom of Viewport**
**AFTER  — Bottom of Viewport**
> fix: signup & billing page scrolling

- src/ui/pages/app-detail-service-scale.tsx
Capitalize `Memory` and show the format `(MB)`
> style: max and min labels

- src/deploy/service/index.ts
We were incorrectly coercing 0 into 1 because 1 was our default when `container_count` was `null`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing
https://aptible.slack.com/archives/C05CMUW3LHX/p1701290462412809
> fix(service): set correct container count

- src/ui/shared/app/app-list.tsx
All our ID columns are left aligned, this change matches this behavior for the App List table
BEFORE
AFTER
> style: left align app ID column

- src/ui/layouts/service-detail-layout.tsx
- src/ui/pages/app-detail-service-scale.tsx
Changes
• Add the word `Show` before `Command` to pattern match
• Capitalize the word `Settings` in `Show Advanced Settings`
BEFORE
AFTER
> style: label tweaks

- src/ui/layouts/service-detail-layout.tsx
- src/ui/shared/app/services-detail.tsx
Make Service Header Component 3 columns & organize related information together by column
BEFORE
AFTER
**Allow descenders to show and not get cutoff**
BEFORE — g, y, p gets cutoff b/c of the overflow hidden
AFTER
> Style services header tweaks

- src/deploy/environment/index.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/pages/styles.tsx
The root `/accounts` endpoint does *not* include any stats besides app and database count for performance reasons.  `/accounts/:id` does include all the stats for an individual account.  This change creates a separate container for stats that we set to our cache only when we fetch an individual account endpoint.  This ensures we always have the correct stats on an account detail page.
> fix(environments): race condition overriding stats on detail page

- src/ui/pages/environment-detail-backups.test.tsx
- src/ui/shared/environment/backup-retention-policy-view.tsx
**Changes**
Add label to default edit backup policy state
BEFORE
AFTER
---
**TODO**
• **Make 0 be the default value** for Yearly Backups in the default and edit states
> style: add label to edit backup policy state

- src/ui/layouts/service-detail-layout.tsx
- src/ui/shared/app/services-detail.tsx
Change `Monthly Cost` and `Cost` to `Est. Monthly Cost` to pattern match
BEFORE
AFTER
> style: change Monthly Cost to Est. Monthly Cost

- src/deploy/service/index.ts
- src/ui/pages/app-detail-services.tsx
- src/ui/pages/services.tsx
- src/ui/shared/app/services-detail.tsx
I also updated the app-detail page's services tab to match.  I removed the `Metrics` button because it's not an action and the Service column already points to it.
> refactor(services): top-level tab should be apps only

- src/ui/hooks/use-env-ops-poller.ts
- src/ui/hooks/use-poller.ts
A recent change to the way we poll operations caused pollers to run even when the user leaves the page -- including when the user is logged out.  This is a regression.  I'm going to focus on re-implementing polling app-wide to prevent us from hitting these endpoints so much.  For now, this should fix the immediate problem.
> fix(poll): cancel pollers when switching pages

- src/app/router.tsx
- src/app/test/security.test.tsx
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/ui/layouts/perm-required.tsx
https://aptible.slack.com/archives/C0237PYRF6D/p1702585423015649?thread_ts=1702584496.093159&cid=C0237PYRF6D
Some of our pages did not have the verify email check so I have reviewed the pages and applied the check where needed.  I also added integration tests to ensure those pages cannot be accessed unless they meet the requirements for access.
We also were not checking for account ownership permissions on some pages so I have enforced that as well -- with tests.
> fix(settings): email must be verified

- src/ui/layouts/service-detail-layout.tsx
- src/ui/shared/app/services-detail.tsx
**Changes**
• Make the service image and ID also a link to the Service Detail page
• Shortened the column label to match other pattern of abbreviating Estimated to Est.
• Default Show Command on Service Detail page to Open
> fix: make service link hit area larger

- src/ui/shared/app/services-detail.tsx
**Changes**
• Add ellipsis to commands longer than 30 characters on Services tables
> fix: add ellipsis to long commands on services page

- src/ui/shared/app/services-detail.tsx
Quick Fix to truncate commands on all services page too
> fix: truncate commands on all services page

- src/ui/shared/app/services-detail.tsx
- src/ui/shared/db/backup-list.tsx
**Changes**
• Adjust colspan on empty services table to span full width
• Adjust colspan on empty environment backups table to span full width
BEFORE
AFTER
> fix: adjust colspan on empty services table to span full width

- src/deploy/activity/index.ts
- src/deploy/activity/selectors.test.ts
- src/ui/shared/activity.tsx
`operation.resource_type` references multiple db tables that can have
overlapping primary key ids.  Previously we were only filtering by
resource id and not also including the resource type, which is necessary
to properly filter operations.
This change requires resource id and type to be provided before showing
operations in any activity table.
> fix(activity): filter by resource type as well as resource id

- src/deploy/operation/index.ts
- src/ui/shared/active-operation-notice.tsx
We were not filtering by resource type so it would show a toast for the wrong resource
> fix: operation toast for app and db

- src/ui/hooks/use-paginate.ts
- src/ui/pages/database-detail-backups.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/resource-list-view.tsx
I moved the loading spinner for backup tables mainly because we didn't have one for environment detail backups and this makes it identical for both.
> style(backups): show server paginated loading spinner

- src/ui/pages/app-detail-service-scale.tsx
Add min and max placeholder values to the Autoscaling form
Various Examples:
> style: add placeholder values to VAS form

- src/ui/hooks/use-paginate.ts
- src/ui/shared/app/app-list.tsx
We made a change late last week to support server-side pagination which shows a loader next to pagination bar.  Well we don't want to show that loader for local pagination.
> fix: don't show loader for local pagination

- src/ui/pages/app-detail-service-metrics.tsx
- src/ui/pages/database-detail-metrics.tsx
**Remove Y Axis chart labels**
• They don't add additional information
• The Y Axis Units already show (ex. %, MB)
• Gives more room for the chart lines
BEFORE
AFTER
> style: remove Y Axis chart labels

- src/ui/shared/cookie-notice.tsx
In Tailwind the highest non-customized z-index value is `z-50`. So `z-100` is invalid & gets ignored.
BEFORE
AFTER
> Fix: Cookie Notice Banner Z-Index

- src/deploy/database-images/index.ts
- src/deploy/operation/index.ts
- src/deploy/service/index.ts
- src/deploy/stack/index.ts
- src/deploy/vpc-peer/index.ts
- src/deploy/vpn-tunnel/index.ts
- src/ui/pages/settings-ssh.tsx
- src/ui/shared/operation-status.tsx
`array.sort()` mutates the array in-place instead of returning a new array so we need to be careful because our store is frozen (immutable, read-only).
> fix: create copy when using `array.sort()`

- src/ui/layouts/role-detail.tsx
- src/ui/pages/role-detail-members.tsx
- src/ui/pages/settings-team-roles.tsx
**Small designs tweaks to roles pages**
• Removed `Name` from the Role Details box b/c we already show it on the page's header
• Changed `Date Added` to `Added Date`
• Changed `Created At` to `Created Date`
• Use our table link token on the roles page
• Removed the plus icon from the Save Role button (none of our save buttons have icons)
BEFORE
AFTER
BEFORE
AFTER
> style: design tweaks

- src/validator/index.ts
In validation, we're currently setting it `IP_WHITELIST_MAX_SIZE=25`, whereas in the[ old UI, it's 50](https://github.com/aptible/deploy-ui/pull/752). Updating for parity, since we now support 50 per AWS quota increase to 120.
> change IP filter allowlist size from 25 to 50

- package.json
- src/deploy/app/index.ts
- src/deploy/configuration/env-vars.test.ts
- src/deploy/configuration/index.ts
- src/projects/index.ts
- src/string-utils/index.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/hooks/use-env-editor.ts
- src/ui/pages/app-detail-config.tsx
- yarn.lock
We need to mirror behavior between converting `deploy-api.Configuration.env` to a string (for our config editor) and converting a string into an intermediary env config list (which we then eventually convert into `deploy-api.Configuration.env`.
- `configEnvToStr`: `({ [key: string]: string | null }): string`
- `configStrToEnvList`: `(string): { key: string, value: string }[]`
- `configEnvListToEnv`: `(envList, curEnv): { [key: string]: string | null }`
So the API is slightly asymmetric in terms of its types, which isn't ideal, but creating a new `deploy-api.Configuration.env` is a little more complicated because we have to remove keys using special logic -- so we need the current config env as well.
> fix(app.config): multiline env var quoting value behavior

- src/deploy/configuration/index.ts
- src/schema/schema.ts
- src/ui/shared/app/config.tsx
When you view the read-only version of an App's configuration it looks different from the edit-view.
> fix(app.config): make view and edit env consistent

- src/projects/index.ts
- src/ui/shared/db/creator-form.tsx
Sometimes we would accidentally add the same database from the url query parameter multiple times causing multiple databases to be added erroneously.
> fix(deploy): only proccess db query params once

- src/ui/pages/logout.tsx
Fix the security settings link on the logout page so it points to `app-ui`
> fix: logout link url

- src/auth/token.ts
We were preventing any security related http requests from happening because of a regression when we decided to revoke all tokens after some security operations.  This commit refactors that work so it functions as expected.
> fix(security): call next mdw when revoking tokens

- src/app/test/app-detail-service-scale.test.tsx
- src/ui/pages/app-detail-service-scale.tsx
Fix typo on scale page: `revieweing` should be spelled `reviewing`
> chore: fix typo on scale page

- src/ui/shared/db/backup-list.tsx
Update final backup pill color styling
**BEFORE** - (Final pills appear as green & blue)
Environment Detail / Backups Tab
---
**AFTER** - (Final pills match the same color)
Environment Detail / Backups Tab
Database / Backups Tab
> fix: database backup pill color styling

- src/auth/pass.ts
- src/ui/pages/forgot-pass.test.tsx
- src/ui/pages/forgot-pass.tsx
- src/ui/pages/settings-profile.test.tsx
- src/ui/pages/settings-profile.tsx
- src/ui/pages/signup.test.tsx
- src/ui/pages/signup.tsx
- src/ui/shared/banner.tsx
- src/validator/index.ts
- https://aptible.zendesk.com/agent/tickets/50991
- https://aptible.zendesk.com/agent/tickets/50992
- Added validation to forgot-pass, signup, and edit name
- Added sanitize function to remove harmful characters
- Modified invalid_email response from forgot-pass to show a `fakeTrue` so a potentially harmful user cannot know whether an email is a user.
- they can still check the network tab but a change in `auth-api` will still be needed
> Security validation fixes

- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/styles.tsx
**Changes**
• Add view docs link for autoscale
• Change default banner styling to info variant & remove default from styles page (we never use default)
BEFORE
AFTER
> chore: add autoscaling doc

- src/ui/hooks/use-env-editor.ts
- src/ui/pages/app-deploy-configure.test.tsx
- src/ui/pages/app-detail-config.tsx
Previously we showed all the environment variables which could cause some unintended side-effects and doesn't really map with how environment variables are set in Apps.  This change aligns more closely with how the CLI functions: it's additive.
I also updated the explainer text to make it more clear how we parse our textarea.
> fix: blank env editor

- src/app/test/app-detail-service-scale.test.tsx
- src/app/test/database-detail-scale.test.tsx
- src/mocks/handlers.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/database-detail-scale.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1707421000506989
> fix(scale): redirect on success

- src/deploy/endpoint/index.ts
- src/ui/pages/app-create-endpoint.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1707366948501139
> fix(endpoint): check container_ports as well

- src/deploy/stack/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/app-create-endpoint.tsx
Instead of hardcoding `on-aptible.com`.
> Show stack default-domain on create endpoint page

- src/auth/loader.ts
- src/auth/signup.ts
- src/mocks/handlers.ts
- src/types/api.ts
- src/ui/pages/signup.test.tsx
- src/ui/pages/signup.tsx
- src/users/effects.ts
- src/users/types.ts
Prevent a new user from signing up and accidentally creating a duplicate org when they have an existing invitation. Instead, show an error message that points them to check their email for an invite.
> Check for existing invitation during signup

- nginx.conf
* security: route 404s to app
PCI compliance scanning also flagged that some 404 URLs returned the default nginx 404 pages. The behavior found was as follows:
https://app.aptible.com/foo returns an app-based 404, e.g.
https://app.aptible.com/foo.js returns an nginx 404, e.g.
We either need a custom nginx 404 page, or allow the app to handle 404s. This PR opts for the latter.
Available on https://app-sbx-jherman.aptible-sandbox.com/
* https://app.shortcut.com/aptible/story/23324
> security: always use app 404

- src/app/router.tsx
- src/deployment/index.ts
- src/mocks/data.ts
- src/routes/index.ts
- src/schema/factory.ts
- src/source/index.ts
- src/types/state.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/source-detail-layout.tsx
- src/ui/pages/__snapshots__/app-detail-deployments.test.tsx.snap
- src/ui/pages/source-detail.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/deployments-table.tsx
- src/ui/shared/docker.tsx
- src/ui/shared/git.tsx
- src/ui/shared/index.ts
This PR implements a Deployments tab on the Source detail page.
Additionally, this PR refactors the git- and docker-related display elements into their own reusable components, and updates existing interfaces (e.g. the app detail page, deployments table, etc) to use them for visual consistency.
* Create a new "Deployments" tab to list all deployments from the source
* Update the app list table to use the new `GitRef`, `GitCommitMessage`, and `DockerImage` components
* Add a "View" button to the app list table for consistency
* Use the new `GitRef`, `GitCommitMessage`, and `DockerImage` components in the detail header and deployments table
* Always show the git commit message in the detail header (to prevent jump/jank on first load)
* Link the source name to the source detail page if the …
> feat: deployments tab for sources

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/deployment-detail-layout.tsx
**Small Spacing Tweak**
Set max height for git commit messages only inside detailbox components on the App Detail and Deployment Detail headers to save vertical space.
This works because we truncate the commit messages to only 30 characters long, and they never wrap to 2 lines.
BEFORE
AFTER
> fix: set max height for git commit messages

- src/ui/shared/deployments-table.tsx
This PR fixes an issue where the source deployments table would show the app's current docker ref instead of the point-in-time ref.
> fix: an issue where the source deployments table would show the current docker ref instead of the point-in-time ref

- src/ui/layouts/deployment-detail-layout.tsx
Use the Deployments image on the Deployments Detail page
> fix: change deployment details logo

- src/ui/layouts/deployment-detail-layout.tsx
This PR updates the Deployment Details page to use the new `GitRef`, `GitCommitMessage`, and `DockerImage` components for visual consistency.
> Update the deployment details layout to use the new common source components

- src/ui/shared/app/app-list.tsx
This PR fixes a mismatch between the "No resources found" colspan and the number of table columns.
> Fix a mismatched colspan for the app list on the Source details page

- src/ui/layouts/app-detail-layout.tsx
This PR removes a query for an app's current configuration on its detail page, which was causing "Access Denied" issues for users that only had basic read permissions.
The query is no longer needed: it was only used to retrieve the name of the app's Docker image, which is now retrieved from the current Deployment instead.
> fix: an issue where users with only `basic_read` permission would receive an access denied error message when viewing app details

- src/ui/pages/app-detail-config.tsx
- src/ui/pages/deployment-detail-config.tsx
This PR fixes a [reported bug](https://aptible.slack.com/archives/C05CMUW3LHX/p1712611841145119) that was attempting to fetch an app using a deployment ID (instead of the deployment's app ID), manifesting as a permission issue.
> fix: a bug preventing some users from viewing deployment configuration

- src/bootup/index.ts
- src/deploy/app/index.ts
- src/deploy/search/index.ts
- src/deployment/index.ts
- src/ui/shared/app/app-list.tsx
This PR implements support for searching and sorting apps on the Sources page based on their current git ref/commit, docker image, and deploy time.
> feat: sort and filter apps by their deployment metadata on the source detail page

- package.json
- src/auth/membership.ts
- src/ui/pages/settings-team-members-edit.tsx
- yarn.lock
fix: reset edit membership form when success
https://aptible.slack.com/archives/C05CMUW3LHX/p1713206044643149
Previously we were submitting all changes to the API in parallel for add and removing memberships for a user.  Because these are all separate API requests, it is possible to run into a race condition where the memberships being removed complete before the requests being added complete.
When a user does not have any memberships for an organization, they are automatically removed.  This is the race issue that can happen.
The second issue happens when the user does multiple rounds of updating a user's roles on the same page.  When the changes are submitted and successfully, we we not properly "resetting" the form which caused weird issues like trying to create a membership that …
> fix: race between adding and removing memberships for user

- src/deploy/log-drain/index.ts
- src/ui/pages/environment-detail-integrations.tsx
papertrail is syslog based: https://github.com/aptible/deploy-ui/blob/d00649b77a9beebc3f1a434106e5f817d4024f46/app/models/log-drain.js#L53
> chore(log-drain): add papertrail to syslog classification

- src/deploy/app/index.ts
- src/deploy/search/index.ts
- src/deployment/index.ts
- src/mocks/data.ts
- src/schema/factory.ts
- src/source/index.ts
- src/types/state.ts
- src/ui/pages/__snapshots__/app-detail-deployments.test.tsx.snap
- src/ui/pages/sources.tsx
- src/ui/shared/git.tsx
- src/ui/shared/tooltip.tsx
This PR adds a sortable "live commits" column to the source list page. This will enable a user to gauge relative activity between sources.
> feat: add live commits column to the source list page

- src/ui/pages/sources.tsx
This PR fixes an annoying issue where sorting by Live Commits may cause the column header to jump left or right depending on the width of the data in the column.
This change makes the width of those cells fixed to prevent that issue.
> Fix the width of the Live Commits column to prevent jumping when sorting

- src/ui/shared/git.tsx
This PR leverages the work in #799 to improve the display of multi-line commit message tooltips.
> fix: improve tooltips for multi-line commit messages

- src/app/router.tsx
- src/deploy/app/index.ts
- src/routes/index.ts
- src/ui/pages/sources-setup.tsx
- src/ui/pages/sources.tsx
- src/ui/shared/select.tsx
This PR introduces a "Source Setup" page. It also adds the Source URL to the source list table.
If a user has no sources, they will be automatically redirected to the Source Setup page, and given instructions on how to set up a source for a selected app.
A user that already has at least one source configured can visit the Source Setup page by clicking the New Source button.
> feat: source setup page

- src/schema/factory.ts
https://app.shortcut.com/aptible/story/24238/display-of-backup-retention-policy-on-a-new-environment-is-wrongly-set-to-0?vc_group_by=day&ct_workflow=all&cf_workflow=500000186
> fix(env): change default values for env backup retention policy

- src/ui/pages/sources.tsx
This PR fixes an issue where a search that returns no results would cause a redirect to the source setup page.
> fix: don't redirect to source setup if search returns no results

- src/ui/pages/database-detail-settings.tsx
added space between "type" and the db name
> Db settings page typo

- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
Currently, an App or Database can appear in the list multiple times so the resource ID is not suitable as the React key. The matching config key is better as it is unique.
> Change dependency list key

- src/ui/pages/stack-detail-vpn-tunnels.tsx
Looks like we accidentally never added the Phase 1 Algorithm to the data we show
> VPN Tunnels - show phase1 algorithm

- src/ui/shared/environment/backup-retention-policy-view.tsx
https://app.shortcut.com/aptible/story/25476/warn-require-confirmation-when-reducing-backup-retention-policy
> Warn user when reducing the number of retained backups

- src/auth/token.ts
- src/ui/pages/logout.tsx
- src/ui/pages/settings-security.tsx
- src/ui/shared/banner.tsx
- src/ui/shared/tokens.ts
Be as clear as possible that "other" is not inclusive of the current session, including avoiding the word "all" entirely.
> Don't say 'all' if it's qualified with 'other'.

- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/database-detail-cluster.tsx
- src/ui/shared/db/database-list.tsx
Switches from Type + Version to the Description, which has more information available that is already intended to be human readable (the same string you use when you _choose_ a database image)
> update database version + type to description

- src/ui/pages/stack-detail-hids.tsx
https://aptible.zendesk.com/agent/tickets/54088
Customer reported that they use our HIDS reports for SOC2, and it's sometimes difficult to track because they're out of order. Updating logic to sort_by `From Date` instead of `Posted Date` by default. 
Before:
After:
> sort by hids start_date by default

- src/api/index.ts
- src/deploy/certificate/index.ts
- src/deploy/endpoint/index.ts
- src/ui/pages/endpoint-detail-settings.test.tsx
- src/ui/pages/endpoint-detail-settings.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1723657960421089
When running `updateEndpoint` we were previously providing *both* the
previously attached `certId` as well as the newly added cert.
This made it so we never actually create the new cert and instead just
use the previous one.
> fix: endpoint settings creating new cert

- src/mocks/handlers.ts
When running `make test` there's a lot of warnings being printed because we don't have some API endpoint mocks.  This PR adds them to suppress those warnings.
> chore: add mock handlers for new api calls

- .gitignore
- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/styles.tsx
https://app.shortcut.com/aptible/story/26534/the-cluster-tab-only-shows-replicas
show link in the db detail page header if the replica has a linked primary
> add primary db link in header for replicas

- src/deploy/backup/index.ts
- src/deploy/search/index.ts
- src/ui/hooks/use-paginate-backups.ts
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/__snapshots__/app-detail-deployments.test.tsx.snap
- src/ui/pages/environment-detail-settings.tsx
- src/ui/pages/services.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/cost-estimate-tooltip.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/tooltip.tsx
- I ran through all the places we show a cost estimate to ensure all of the necessary data is being pulled especially backups since they're not loaded on bootup.
- Moved fetching backups to per-database and per-environment in their lists so that we don't have to wait on all backups to get estimates. Stack estimates still require waiting for all backups to be fetched.
- Moved the cost loading spinner from headers to the cost themselves to make it extra clear when the cost has finished calculating (see screenshot below).
> Improve backup load performance and show spinner until estimate is calculated

- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
React hooks cannot be conditional, they always need to run in the same order on each render of the component
> Fix cost issues

- src/ui/shared/db/backup-list.tsx
https://github.com/aptible/deploy-ui/blob/7c738cfb80f8ffd3a7d70b27770e5181c552964c/app/components/backup-item/template.hbs#L8
> fix(env): show correct backup label on backups tab

- src/ui/pages/role-detail-environments.tsx
Changed primary **Save** button into a white **Close** button so it doesn't look like its a required form submission action b/c the form auto-saves.
> change-save-to-close

- src/app/test/no-payment-found.test.tsx
- src/deploy/plan/index.ts
- src/mocks/data.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/create-stack.tsx
- src/ui/pages/plans.test.tsx
- src/ui/shared/plan.tsx
This PR changes the plans we show on /plans to match . The new plans already exist in deploy-api in production (see related aptible/deploy-api#1586). Note that the new Development and Production plans **have no included resources and no base fee.** This is intentional, and should make it easier to simplify or deprecate `ActivePlans` in the future.
To show how the /plans change will change for existing users, I created a Notion doc showing the before/after for (nearly) every type of plan/payment info combination that exists today. 👉 [**QA: Changes to /plans** (Notion)](https://www.notion.so/aptible/QA-Changes-to-plans-120509e56b41805db918c165be910f8e)
The approach of making no changes to deploy-api has one downside: customers can "downgrade" to Development even if they have an existing …
> Update plans to Development/Production/Enterprise without deploy-api code changes

- src/app/test/app-detail-service-scale.test.tsx
- src/deploy/service-sizing-policy/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/app-detail-service-scale.tsx
Depends on https://github.com/aptible/deploy-api/pull/1593
Also changed the policy summary, these new fields ONLY show up if they're not a value of `1`
> Add scale_up_step and scale_down_step inputs for HAS

- src/ui/pages/app-detail-service-scale.tsx
- change type to text
- add pattern and inputMode as well
Reason for fixing
https://www.loom.com/share/c86884c64c324a0fb79f9cfc7455e343?sid=c173aeb2-8c12-470a-bbc8-5797266dc841
Once this is merged and deployed, I will be going back and changing all number inputs to text.
> change container scale input to text

- src/ui/shared/settings-sidebar.tsx
Add conditional to prevent SCIM / Provisioning menu item when the organization is in trial with no payment:
https://app.shortcut.com/aptible/story/29074/limit-scim-access-to-paid-plans-only
> block SCIM access for trial orgs

- src/app/test/database-detail-scale.test.tsx
- src/deploy/database/index.ts
- src/ui/pages/database-detail-scale.tsx
There's a validation on deploy-api to make sure there are 7 hours in-between disk resizes, but since we always send disk_size, the validation assumes ALL scale operations resize the disk. This fixes that
> Do not send disk-size on DB scale unless it has changed

- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/app-detail-service-metrics.tsx
For any given App or DB service, we fetch a page's worth of Releases (e.g. 40 releases).  If a user performs a rollback to a previous release that is outside the last 40 releases then we were not pulling those metrics.
This PR ensures that we always fetch the current release for a service.
> fix(metrics): always fetch the service's current release

- src/api/index.ts
Right now we have `debugMdw` which uses a conditional logger.  Not everyone uses the conditional logger and sometimes there's errors in those logs that should be raised to the developer.
This change will run `console.error` anytime there is an API fetch error so it is easier to see in our debugger.
> chore: log fetch errors from api

- src/ui/pages/diagnostics-create.tsx
This PR makes a couple of small tweaks to the UI based on @joeclayallday's suggestions:
1. Padding above the Issue Description header was reduced for consistency
2. Labels were added above the start and end times in the time picker
> Diagnostics UI tweaks

- src/ui/layouts/app-detail-layout.tsx
- src/ui/shared/application-sidebar.tsx
This PR fixes an issue that was causing an intermittent error when refreshing the page in some parts of the app.
In React, you can't call hooks conditionally. For whatever reason, this particular style of conditional use was not caught by any of the local development guardrails, and does not raise an error until built into a production bundle.
> Fix a hook usage violation

- src/ui/shared/app/services-detail.tsx
This PR removes the "Diagnose Issues" button on the services tab of the app details page.
> Remove the Diagnose Issues button on the services tab

- README.md
- src/app/test/accept-invite.test.tsx
- src/validator/index.ts
* fix: assert passwords are at most 72 bytes
* docs: update README with hot protips
Bcrypt truncates passwords after 72 bytes. This PR restricts maximum password length to 72 bytes instead of 72 characters.
In lieu of a full battery of signup tests, this appends on to `app-ui/src/app/test/accept-invite.test.tsx` and asserts that adding a password that's too long followed by a good password works as intended.
* https://github.com/aptible/auth-api/pull/630
* https://app.shortcut.com/aptible/story/24975
> fix: assert passwords are at most 72 bytes

- src/deploy/operation/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1738592209907599
> fix: ability to filter by Service in App or Database activity pages

- .github/workflows/deploy.yml
- .github/workflows/staging.yml
Apparently the `build-args` option of the `docker/build-push-action` treats quotes literally. This PR removes them for the `VITE_APTIBLE_AI_URL` values.
> Remove quotes from build-args in the deployment workflows

- src/chart/chartjs-plugin-annotations.ts
Fixes an error where charts would not display if there were no annotations: https://aptible.slack.com/archives/C03R1L20YSW/p1738860094160489
> Force chart annotations to be an array

- src/ui/shared/diagnostics/line-chart.tsx
This PR fixes [#31132](https://app.shortcut.com/aptible/story/31132/synchronized-chart-popovers-don-t-disappear-when-a-user-stops-hovering), where synchronized chart popovers would remain even after the user's mouse stops hovering a chart.
> Clear synchronized ChartJS popovers when the mouse leaves a chart

- src/ui/shared/diagnostics/resource.tsx
This PR cleans up the charts on the diagnostic dashboard page: 
- Removes the Y axis label since it's represented in the tick labels
- Remove the interpretation section (it's for the LLM) and use its styling for a toggleable analysis section instead
> ⚠️ Note: this pairs with https://github.com/aptible/hotshot/pull/11, which adds some fidelity to the plot title.
> Diagnostics chart cleanup

- src/aptible-ai/index.ts
- src/ui/hooks/use-dashboard.ts
- src/ui/shared/diagnostics/line-chart.tsx
- src/ui/shared/diagnostics/resource.tsx
This PR fixes a subtle bug that was causing axes of the charts to become misaligned, and sometimes rendering charts with multiple series improperly.
Here's an example, where the `billing_events` service of `sbx-main-deploy-api-background` had restarted with a new container ID. The existing implementation overlays the series, even though the second container's metrics should come after the first.
> Fix chart axes and improper combination

- src/deploy/service-sizing-policy/index.ts
- src/schema/factory.ts
- src/ui/pages/app-detail-service-scale.tsx
This won't actually go out until the deploy-api side is released, but in preparation, we want to make sure the interfaces have updated language and defaults.
https://github.com/aptible/deploy-api/pull/1684 and https://aptible.slack.com/archives/C022BUSF0B1/p1738846349350639 for full context.
> Update autoscaling UI wording and defaults for post release cooldown

- src/ui/hooks/use-dashboard.ts
- src/ui/pages/diagnostics-detail.tsx
- src/ui/shared/diagnostics/resource.tsx
This PR adds support for displaying "ranked" plots (e.g., those that Hotshot found interesting and potentially correlated) and summary text.
> ⚠️ This PR must accompany https://github.com/aptible/hotshot/pull/12 when deployed.
> Add support for displaying correlated anomalies and summaries for diagnostic dashboards

- src/ui/hooks/use-dashboard.ts
- src/ui/pages/custom-resource-detail.tsx
This PR adds the diagnostics creation form to the custom resource detail page, and updates the websocket connection to include the resource type as a parameter.
> Add the diagnostics creation form to the custom resource detail page

- src/ui/shared/service-pricing-calc.tsx
The service pricing calculator was displaying "1 x" for container count in the cost breakdown, regardless of the actual number of containers configured. This made the cost breakdown confusing when services were scaled to multiple containers.
Updated the service pricing calculator to use `service.containerCount` instead of the hard-coded "1 x" value. This ensures the cost breakdown accurately reflects the actual number of containers being used.
1 x 7 GB container x $0.05 per GB/hour = $4,943.20/month
2 x 7 GB container x $0.05 per GB/hour = $4,943.20/month
> Fix: Service Pricing Calculator Shows Actual Container Count

- src/app/router.tsx
- src/deploy/entities.ts
- src/deploy/llm-integration/index.ts
- src/routes/index.ts
- src/schema/factory.ts
- src/schema/schema.ts
- src/types/deploy.ts
- src/ui/pages/index.ts
- src/ui/pages/settings-team-llm-integrations-add.tsx
- src/ui/pages/settings-team-llm-integrations-edit.tsx
- src/ui/pages/settings-team-llm-integrations.tsx
- src/ui/shared/settings-sidebar.tsx
This PR adds a UI for configuring LLM integrations (visible to orgs with `hasBetaFeatures` or `hasDiagnosticsPoc`). It supports:
- OpenAI
- Azure
- Anthropic
- AWS Bedrock
Depending on the provider chosen, the form and validations change:
LLM Integrations can be edited and deleted:
> UI for configuring LLMs

- src/aptible-ai/index.ts
- src/ui/pages/diagnostics-detail.tsx
This PR adds the resource name to each plot in the diagnostic summary, and fixes an unlikely-but-possible overlap bug when two resources of different types have the same ID.
> Make diagnostic plot summary labels more descriptive

- src/app/router.tsx
- src/deploy/edge/index.ts
- src/routes/index.ts
- src/ui/pages/custom-resource-detail.tsx
- src/ui/pages/custom-resources.tsx
- src/ui/pages/home.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/dependencies/custom-nodes.tsx
- src/ui/shared/dependencies/edges.tsx
- src/ui/shared/dependencies/graph.tsx
- src/ui/shared/dependencies/node.tsx
- src/ui/shared/dependencies/single-resource-item.tsx
A handful of improvements to the Software Catalog, in separate commits:
- Rename UI label and route from Custom Resources -> Software Catalog
- Update resource icons to match currently existing resource types
- Add resource type to React Flow node display
- Show all edge types, not just depends_on
- Annotate edges in React Flow diagrams with relationship_type
- Correctly route to /software-catalog from / if selectHasDiagnosticsPocFeature
- Add ability to filter by resource type to Software Catalog
Loom showing the improvements here: https://www.loom.com/share/77bded5ddf334a548c6163e68a275e59
I had a commit that rendered resource nodes in different colors by resource type (12988c56acc28f7ef2fea4afbfe0b10c225e16b7) but on second thought I removed it: I think the addition of logos makes the …
> [sc-32581] Software Catalog improvements

- src/ui/pages/stacks.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/table.tsx
Adds a total estimated monthly cost row to both the Environments and Stacks tables. The total:
- Appears at the bottom of each table when there are items listed
- Sums costs across all pages of filtered results
- Uses the existing cost tooltip component with clarifying text about what's included
- Maintains consistent styling with the rest of the table using TFoot
> add total cost row to environment and stack tables

- src/deploy/endpoint/endpoint.test.ts
- src/deploy/endpoint/index.ts
- src/mocks/data.ts
- src/types/deploy.ts
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/endpoint-detail-settings.test.tsx
- src/ui/pages/endpoint-detail-settings.tsx
- src/validator/index.ts
[sc-32570]
This PR allows `container_ports` to be edited for TCP and TLS endpoints. The current iteration of the endpoint edits forms only changes `container_port,` which is not relevant for TCP and TLS endpoints and hits a validation error. 
It also changes the port validation from using `Number.parseInt` to just `Number,` since the former has weird behavior — for example, `8asdfsadfsaf` would be considered `8` by the validator.
> make container ports editable for tcp/tls endpoints

- src/ui/pages/diagnostics-create.tsx
- src/ui/pages/diagnostics.tsx
These fixes were identified during a recent customer convo, and all seem legit. 
Including:
* Impacted time range is set in user's local time, and then sent to the server in UTC
* Symptoms are free-form text, not a drop down
* The list of dashboards correctly identifies "Time Created", and adds the "Time Range"
For the final bullet point, this may not be correct anymore when we shift to a single timestamp (timestamp issues were noticed). However, I'm not sure whether we want to display the single timestamp or the range identified by the diagnostic process in those scenarios, so I'm keeping the time range for now.
> Made small QOL improvements for diagnostics dashboards

- src/ui/layouts/endpoint-detail-layout.tsx
[sc-32780]
Adding placement information to the header for Database Endpoints. 
This information was already displayed from the Database's endpoint tab, but not from the Endpoint-specific header.
> add placement to database header info

- src/app/test/create-metric-drain.test.tsx
- src/deploy/metric-drain/index.ts
- src/ui/pages/create-metric-drain.tsx
[sc-32711]
Similar to Log Drains, Datadog Metric Drains can be in different sites. Allow this to be configured on metric drain creation in the UI. 
A difference between this and our CLI `--site` is that this updates series_url regardless. If no site is explicitly stated in the CLI, we assume US1 but don't set series_url.
> add site selection for datadog metric drains

- src/deploy/support/index.ts
- src/ui/pages/support.tsx
This PR improves the user experience of the support form by addressing two issues:
- Line break preservation: Message text now maintains formatting when submitted by converting newlines to HTML <br /> tags
- File upload error handling: Better error visibility for attachment uploads, showing clear feedback when files are rejected
- Added conversion of newlines to HTML <br /> tags in support form messages before submission
- Implemented error state management for file uploads with a dedicated error banner
- Extended the API interface with an error callback mechanism to properly surface API errors
- Applied consistent error styling using the existing Banner component
1. Line break preservation:
- Enter a message with multiple paragraphs in the support form
- Submit the form and verify line …
> Support form fixes: line breaks and attachment error display

- src/ui/pages/create-database.tsx
- src/ui/shared/db/scale-options.tsx
Elasticsearch databases can't start without at least 1GB of memory. This PR removes that option on the create database page when elasticsearch is selected as the type.
> Require new elasticsearch databases to have at least 1GB of memory

- src/ui/pages/database-detail-settings.tsx
Improve clarity on language around disabling db backups, to clarity that it will also prevent final backups from being made when the database is deprovisioned. Hold for @benjodo to merge.
> improve clarity on disabling db backups

- src/ui/shared/footer.tsx
[sc-33096]
Remove legacy dash link from footer:
> remove legacy dashboard link

- src/ui/pages/billing-method.tsx
- src/ui/pages/billing-method.validators.test.tsx
[sc-32264]
We previously required that a state be selected even when Canada was the chosen country in the billing form. [Confirmed](https://aptible.slack.com/archives/C022BUSF0B1/p1746495292254529?thread_ts=1746473082.801859&cid=C022BUSF0B1) with Finance that we do not require state/province information from Canadian customers.
> Remove state validation for Canada on billing method form

- src/deploy/database-credential/connection-url-rewrite.test.ts
- src/deploy/database-credential/index.ts
Previously our regex was looking for a trailing `/` which only works for connection URLs with a database selector, like postgres.
Many connection URLs do not have a database selector which meant we were not properly replacing their hostnames.
In this revised approach, I use a negative lookahead regex to properly find the last occurence of a `:[0-9]`
> fix(endpoints): replace hostname in credential without a db selector
