aptible/app-ui

- src/ui/pages/signup.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/endpoints-overview.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/settings/team-list-view.tsx
- icon file exporting all icons
- swapped `icn` out for icons
- added magnifying glass to search bar
> initial icons

- src/ui/shared/icons.tsx
- add props interface
- update `any` -> `Props`
- optional props like `color`
- described component further with `React.FC<Props>`
> refactor icon props components for linter

- src/ui/shared/application-sidebar.tsx
- src/ui/shared/button.tsx
- src/ui/shared/endpoints-overview.tsx
- src/ui/shared/link.tsx
- src/ui/shared/tokens.ts
- src/ui/shared/user-menu.tsx
- tailwind.config.cjs
> chore: update application sidebar

- index.css
- src/app/router.tsx
- src/app/store.ts
- src/ui/layouts/settings-page.tsx
- src/ui/pages/create-project.tsx
- src/ui/pages/elevate.tsx
- src/ui/pages/login.tsx
- src/ui/pages/settings.tsx
- src/ui/pages/signup.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/link.tsx
- src/ui/shared/table.tsx
- src/ui/shared/tokens.ts
- src/ui/shared/user-menu.tsx
- tailwind.config.cjs
> Design app sidebar

- package.json
- src/api/index.ts
- src/auth/accept-invitation.ts
- src/auth/signup.ts
- src/auth/token.ts
- src/bootup/index.ts
- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/environment/index.ts
- src/hal/index.ts
- src/invitations/invitations.ts
- src/mfa/index.ts
- src/organizations/index.ts
- src/projects/index.ts
- src/users/effects.ts
- yarn.lock
This provides much better types for our effects
> refactor: update saga-query

- src/deploy/operation/index.ts
- src/types/deploy.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/icons.tsx
https://aptible.slack.com/archives/C022BUSK487/p1676402464109179
> ftux status rely ops

- package.json
- src/api/index.ts
- src/deploy/operation/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/aptible-logo.tsx
- src/ui/shared/box.tsx
- src/ui/shared/icons.tsx
- yarn.lock
> feat(ftux): show operation logs

- src/ui/pages/create-project-git.tsx
- src/ui/shared/tokens.ts
> feat(ftux): next steps after successful deployment

- src/api/index.ts
- src/projects/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/pages/create-project.tsx
- src/ui/pages/login.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/modal.tsx
- src/ui/shared/settings/team-list-view.tsx
- src/ui/shared/tokens.ts
- src/ui/shared/user-menu.tsx
- tailwind.config.cjs
- tsconfig.json
> Icons revamp

- package.json
- src/deploy/app/index.ts
- src/deploy/configuration/index.ts
- src/deploy/database/index.ts
- src/projects/index.ts
- src/types/deploy.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/box.tsx
- src/ui/shared/form-group.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/tokens.ts
- yarn.lock
We also allow the user to make changes to environment variables and service commands without re-provisioning databases.
We also require user to provide a database handle instead of generating one for them.
https://user-images.githubusercontent.com/1940365/221024042-44da351e-be69-45f0-8056-9aa0a87e9df2.mp4
> feat(ftux): show back button on status page when there's a failure

- package.json
- src/auth/index.ts
- src/auth/login.ts
- src/auth/signup.ts
- src/auth/token.ts
- src/auth/webauthn.ts
- src/types/loader.ts
- src/ui/pages/login.tsx
- yarn.lock
This feature makes it possible to login using a security instead of OTP.
This shows the flow, there's an error because it's really hard to test locally.
https://user-images.githubusercontent.com/1940365/221666932-91a3755b-56de-49e2-b30d-5cc1df1ea493.mov
> webauthn login

- src/deploy/app-service-definitions/index.ts
- src/deploy/app/index.ts
- src/deploy/code-scan-result/index.ts
- src/deploy/configuration/index.ts
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/deploy/operation/index.ts
- src/hal/index.ts
- src/projects/index.ts
- src/types/helpers.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/app/endpoints-detail.tsx
- src/ui/shared/environment/environment-activity.tsx
- src/ui/shared/form-group.tsx
- src/ui/shared/tokens.ts
https://user-images.githubusercontent.com/1940365/223149104-91b79431-2b91-47c0-9029-2400f3dfb240.mp4
> feat(ftux): create default endpoint after app deploys successfully

- .dockerignore
- Dockerfile
Docker image is failing to build
> Fix docker image failing to build

- Makefile
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/deploy/index.ts
- src/deploy/operation/index.ts
- src/projects/index.ts
- src/types/deploy.ts
- src/ui/pages/create-project-git.tsx
Story details: https://app.shortcut.com/aptible/story/10730
> feat: [sc-10730] Fault tolerance for provisioning resources during FTUX

- src/deploy/endpoint/index.ts
- src/ui/pages/create-project-git.tsx
A couple of bug fixes I noticed when going through FTUX flow today.
> Fix redeploy when no deploy op

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/shared/add-ssh-key.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/pre-code.tsx
- src/ui/shared/tokens.ts
I also updated the default button styles to match spec
> style(ftux): ssh add key screen updates

- .husky/pre-commit
- package.json
- src/deploy/database/index.ts
- src/deploy/service/index.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/pages/app-detail.tsx
- src/ui/pages/db-detail.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/endpoints-overview.tsx
- src/ui/shared/tabs.tsx
- tsconfig.json
- yarn.lock
enables `noUnusedLocals` and removes precommit hooks
> enforce no unused locals and remove precommit hooks

- src/ui/pages/create-project-git.tsx
- src/ui/shared/box.tsx
I also added progress text that we can continue to design
https://user-images.githubusercontent.com/1940365/230656339-e4761fdc-7062-4e03-85eb-d56a0bb5e4f6.mov
> design(ftux): remove prev and next buttons for production

- src/api/index.ts
- src/auth/login.ts
- src/auth/logout.ts
- src/deploy/operation/index.ts
- src/deploy/service/index.ts
- src/ui/layouts/elevate-required.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/shared/button.tsx
fix: logout will delete elevated token as well
fix: runtime errors relating to nullables from api
design: add ssh key screen has correct height
feat: login now elevates token automatically
> feat(ftux): view project -> deploy-ui

- src/status-variant/index.ts
- src/ui/pages/add-security-key.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/otp-setup.tsx
- src/ui/shared/banner.tsx
- src/ui/shared/external-link.tsx
> design(ftux): code scan result banners

- .env.example
- .github/workflows/staging.yml
- Dockerfile
- README.md
- src/env/index.ts
- src/types/state.ts
- src/ui/layouts/auth-required.tsx
- src/vite.d.ts
chore: added redirect if user is not currently logged in to existing dashboard (token expires)
enabled flag
empty flag
> sc-11819 - kickout to dashboard if not auth

- README.md
- src/ui/pages/create-project-git.tsx
> design(ftux): new nav bar for ftux flow

- src/deploy/environment/index.ts
- src/deploy/operation/index.ts
- src/routes/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/pages/elevate.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/button.tsx
- src/ui/shared/pre-code.tsx
- src/ui/shared/select.tsx
- src/ui/shared/tokens.ts
design(ftux): updated copy and design elements
https://user-images.githubusercontent.com/1940365/233132910-c7bbf189-9d6b-4004-bef0-8b04fdc2c303.mov
> fix(ftux): simplified status fetching logic

- src/deploy/database/index.ts
- src/projects/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/banner-messages.tsx
fix(ftux): properly handle resource limit errors
Now when we create a database but fail to provision (e.g. resource limit error) we can properly recover from it by clearing resources and retrying.
> fix(ftux): recover when db created but not provisioned

- src/ui/pages/create-project-git.tsx
- src/ui/shared/pre-code.tsx
- src/ui/shared/select.tsx
- src/ui/shared/tokens.ts
> fix(ftux): ux and bug fixes

- src/app/store.ts
- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/environment/index.ts
- src/deploy/operation/index.ts
- src/projects/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/shared/pre-code.tsx
https://app.shortcut.com/aptible/story/12919/onboarding-status-should-denote-start-of-operation-not-success
> onboarding status, service command fixes, and ux fixes

- src/ui/pages/create-project-git.tsx
* responsive is fine
* overflow/scrolling seems unaffected
before:
after:
> chore: updated styling on navigation bar to include shadow

- src/ui/pages/create-project.tsx
> chore: updated to include logo on common entry point

- src/auth/login.ts
- src/bootup/index.ts
We weren't fetching all the on load data after the user logs in.
> fix(login): always fetch

- src/organizations/index.ts
- src/ui/pages/create-project-git.tsx
Repro:
- Try to provision a DB
- Plan limits exceeded
- Deprovision resources
- Go back
- Try to save and deploy again
- No db operation in the status list
Other Fixes:
- sort orgs by updated_at
- properly split env var text area
> fix(ftux): recover from db failing to provision

- src/app/router.tsx
- src/ui/pages/create-project-git.tsx
https://user-images.githubusercontent.com/1940365/235189713-8c084574-4b2b-4d95-ba88-a1c3841de276.mov
https://user-images.githubusercontent.com/1940365/235189677-dc382e7e-ebb3-4b58-9431-0042dc00ede8.mov
> style(ftux): cleanup setup and landing page

- src/ui/pages/create-project-git.tsx
- src/ui/shared/onboarding-link.tsx
https://user-images.githubusercontent.com/1940365/235527775-ea5c9d5d-b668-4c51-be42-70858d697276.mov
> fix(ftux): always allow user to go back to ftux status page

- src/ui/pages/create-project-git.tsx
Name changes from Joe's request:
Clicking on this link will take you back to home page:
> chore: assorted QA adhoc

- src/ui/pages/create-project-git.tsx
> chore: changed banner in anticipation of builder release

- .github/workflows/staging.yml
Enabling flag to view tuna calls in staging env
> chore: updated to set tuna on staging

- src/ui/pages/create-project.tsx
- src/ui/pages/logout.tsx
Misc edits from @joeclayallday :
**Log out copy improvements**
url is valid:
---
text font weight changes on button as requested
> chore: misc copy edit changes

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/db-detail-scale.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/pages/login.tsx
- src/ui/pages/signup.tsx
- src/ui/shared/input.tsx
- src/ui/shared/tokens.ts
> chore: feedback minor qa

- package.json
- src/deploy/operation/index.ts
- src/test/index.tsx
- src/test/setup.ts
- src/ui/pages/create-project-git.tsx
- src/ui/pages/deployments.test.tsx
- src/ui/shared/onboarding-link.tsx
- yarn.lock
https://github.com/aptible/app-ui/assets/1940365/b6ead533-aaac-47ff-b1cc-e28d98dbe124
> Deployments ux

- src/app/test/create-project.test.tsx
- src/deploy/service/index.ts
- src/mocks/data.ts
- src/ui/pages/create-project-git-status.test.tsx
- src/ui/pages/create-project-git.tsx
This should help users better understand what they are provisioning as well as give them some information to debug if they selected the incorrect service to provision and HTTPS endpoint.
> feat(ftux): show current vhosts on status page

- .github/workflows/staging-nextgen.yml
- README.md
corresponds to internal PRs, doing this first before production release
> chore: updated deploy for staging

- .github/workflows/deploy-nextgen.yml
@neurosnap - the prod aptible app needs to be renamed from `cloud-ui` to `app-ui-nextgen`
Please verify it is the desired nextgen appP
> chore: added prod release on tag, renamed staging workflow

- src/ui/pages/create-project-git.tsx
While not completed or failed:
When completed/failed:
> chore: added timer on operations to prevent user from thinking the page is frozen (sc-13947)

- src/ui/layouts/hero-bg-layout.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/create-project.tsx
- src/ui/pages/elevate.tsx
- src/ui/pages/logout.tsx
- src/ui/shared/error-boundary.tsx
Logout
Create Project
Error
Elevate
Ftux onboarding flow
edit - deleted this image, see below, had dummy creds
Create project
edit - deleted this image, see below, had dummy creds
> chore: added common layout to other pages

- src/ui/pages/logout.tsx
on press, logs out:
cannot currently log out on staging, not sure why it's a form
> chore: corrected logout behavior

- src/app/test/create-project.test.tsx
- src/mocks/handlers.ts
- src/test/index.tsx
- src/ui/pages/create-project-git-settings.test.tsx
- src/ui/pages/create-project-git.tsx
> style(ftux): settings page

- .github/workflows/deploy-nextgen.yml
updated for deploying to nextgen production subdomain
> chore: updated nextgen-deploy tag

- src/mocks/handlers.ts
- src/ui/pages/verify-email.test.tsx
Doing in this PR to avoid adding distracting changes to parent PR (settings / deprovision / change name)
> chore: added some tests to pending PR

- src/deploy/code-scan-result/index.ts
- src/ui/pages/create-project-git.tsx
Only appears if data found. This is mainly untracked but a possible option for users:
> chore: added codescan results to frontend optionally

- src/ui/pages/create-project.tsx
> chore: show navbar if user is logged in on `/create`

- src/app/router.tsx
- src/routes/index.ts
- src/ui/pages/impersonate.tsx
- src/ui/shared/settings-sidebar.tsx
- src/ui/shared/user-menu.tsx
> design(nextgen): promote impersonate page to app sidebar

- src/deploy/activity/index.ts
- src/deploy/activity/selectors.test.ts
- src/deploy/operation/index.ts
- src/hal/index.ts
- src/ui/layouts/op-detail-layout.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
This mainly fills the data better inside the activity dashboard.
> chore: ux tweaks

- src/ui/shared/activity.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/resource-table.tsx
Add links to environments in table cell
> design: ux tweaks

- src/ui/shared/app/services-detail.tsx
- src/ui/shared/environment/environment-list.tsx
* env highlighting removed for dev envs:
* fix weird highlighting issues on service list:
> chore: env highlighting changed

- src/ui/pages/db-detail-scale.tsx
- src/ui/pages/environment-detail-certificates.tsx
- src/ui/pages/environment-detail-resources.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/endpoints-overview.tsx
Either via disabled attributes, comments or deletions, non-actionable buttons/inputs are now disabled
> chore: removed or disabled inputs where there is no actionable outcome

- src/app/router.tsx
- src/routes/index.ts
- src/ui/pages/styles.tsx
- src/ui/shared/log-viewer.tsx
Added this to start iterating, only available on nextgen app for now.
> chore: added styles page for reviewing designs

- src/ui/layouts/hero-bg-layout.tsx
- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/endpoints-overview.tsx
- src/ui/shared/form-group.tsx
- src/ui/shared/input.tsx
- src/ui/shared/tokens.ts
Note: these are found at bottom of this doc: https://www.notion.so/aptible/App-UI-Bugs-a386eb0d325d410a93717c6d91de0466
ex: on expanded menu on small screens:
footer spacing:
Icons to styleguide dump:
> chore: assorted QA and minor changes caught internally

- src/ui/shared/app/services-detail.tsx
> chore: dropped sorts for services causing callback depth issues

- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/environment/environment-activity.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/form-group.tsx
- src/ui/shared/resource-list-view.tsx
Dropped the stack type in environment list:
Example of activity table change:
Deploy border change:
Labels and minor style guide changes
> chore: design fixes across the board from more QA

- src/ui/pages/styles.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/index.ts
- src/ui/shared/org-picker.tsx
> feat(sidebar): add org and user name

- src/ui/shared/activity.tsx
Add backup image thumbnail so it shows on the activity pages.
> add-backup-image

- src/app/router.tsx
- src/deploy/disk/index.ts
- src/deploy/image/index.ts
- src/routes/index.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/index.ts
- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/layouts/op-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/deployments.tsx
- src/ui/pages/index.ts
- src/ui/pages/settings.tsx
- src/ui/pages/stack-detail-environments.tsx
- src/ui/pages/stack-detail-vpc-peering.tsx
- src/ui/pages/stack-detail-vpn-tunnels.tsx
- src/ui/pages/stack-detail.tsx
- src/ui/pages/stacks.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/index.ts
- src/ui/shared/resource-list-view.tsx
- src/ui/shared/tabs.tsx
> reactor: detail header components

- src/routes/index.ts
- src/ui/layouts/environment-detail-layout.tsx
This should correctly redirect, note the URL:
---
> chore: corrected url error

- src/ui/pages/environment-detail-integrations.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/index.ts
- src/ui/shared/secret.tsx
> chore: added secrets expandable viewer

- src/ui/shared/user-menu.tsx
This will drop you off here:
Equivalent menu item to this:
---
> chore: added settings link to sbx-main as these panes are not ready

- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-integrations.tsx
> chore: dropped credentials col (for now), and added to db page

- Dockerfile
- src/app/router.tsx
- src/metric-tunnel/index.ts
- src/routes/index.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/container-metrics-table.tsx
Correctly uses the arg, this was missed in the prior PR
DB tables:
Apps still work:
> feat: added db metrics and corrected build args

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/detail-page-header-view.tsx
Fix View Docs Button Spacing
BEFORE
AFTER
> Tweak-Button-Spacing-jc

- src/ui/layouts/op-detail-layout.tsx
Remove mailto links from app
AFTER
> Remove-Mailto-Links

- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
Example with stacks:
---
Also for other resources:
dbs
envs
apps
backups
> sc-15396 - search persisting via qsp

- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
singulars/zeroes:
---
plurals:
> chore: fix plurality of some things on env/db pages

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/styles.tsx
Add IDs to all header cards so its uniform
> Add IDs to every header card

- src/ui/layouts/menu-wrapped-page.tsx
- src/ui/pages/apps.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/shared/feedback.tsx
- src/ui/shared/footer.tsx
- src/ui/shared/index.ts
ToDo
• Turn footer into a shared component
• Make share feedback form show once "Share Feedback" link is clicked & make this a toggle
• Link to appropriate spots
• Add to every page (except FTUX)
> sc-16678-Footer-Styles

- src/app/packages.ts
- src/app/router.tsx
- src/app/store.ts
- src/reset-store/index.ts
- src/routes/index.ts
- src/search/index.ts
- src/types/state.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/index.ts
- src/ui/pages/search.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/index.ts
- src/ui/shared/input.tsx
- src/ui/shared/stack.tsx
- src/ui/shared/tokens.ts
https://github.com/aptible/app-ui/assets/1940365/cd31e86b-4def-4cba-8a4a-6fb7197c054b
> feat: omnisearch

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
Clean up spacing inside our settings cards
> Settings card styling

- src/deploy/container/index.ts
- src/deploy/release/index.ts
- src/deploy/release/selectors.test.ts
- src/metric-tunnel/index.ts
- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/container-metrics-chart.tsx
- src/ui/shared/container-metrics-table.tsx
Note: this requires other changes first on deploy-api and on metrictunnel backends. do not merge until those go in!
Apps
---
CPU:
LA:
---
DB:
CPU:
Memory:
> feat: cross-release charting capability

- .github/workflows/deploy.yml
- .github/workflows/staging.yml
this will not work without correct references to metrictunnel
> chore: correct deploy for apps (which now use nextgen)

- src/ui/pages/app-detail-service.tsx
- src/ui/shared/container-metrics-chart.tsx
full screen and/or hides legend when more containers/data present
everything shows if less to display
> chore: added more dynamism to chart (will expand/hide legend) when more series loaded

- src/deploy/container/index.ts
- src/deploy/service/index.ts
- src/metric-tunnel/index.ts
- src/ui/pages/app-detail-service.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/shared/container-metrics-chart.tsx
https://github.com/aptible/app-ui/assets/1940365/601bcc75-3a63-4471-a4cf-79d898ba0fba
> Metrics batching

- package.json
- src/auth/pass.ts
- src/auth/token.ts
- src/deploy/app/index.ts
- src/deploy/backup-retention-policy/index.ts
- src/deploy/backup/index.ts
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/deploy/index.ts
- src/deploy/state.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/types/deploy.ts
- src/types/state.ts
- src/ui/pages/db-detail-backups.tsx
- src/ui/pages/environment-detail-backups.test.tsx
- src/ui/pages/environment-detail-backups.tsx
- src/ui/pages/logout.test.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/db/index.ts
- src/ui/shared/environment/backup-retention-policy-view.tsx
- src/ui/shared/environment/index.ts
- yarn.lock
> feat: read and edit backup retention policy

- src/app/router.tsx
- src/date/index.ts
- src/deploy/backup/index.ts
- src/deploy/database/index.ts
- src/routes/index.ts
- src/sort/index.ts
- src/ui/pages/app-detail-service.tsx
- src/ui/pages/backup-restore.tsx
- src/ui/pages/db-detail-backups.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/pages/index.ts
- src/ui/shared/activity.tsx
- src/ui/shared/banner.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/db/creator-form.tsx
- src/ui/shared/form-group.tsx
- src/ui/shared/loading.tsx
- src/ui/shared/select-environments.tsx
- src/ui/shared/select.tsx
- src/validator/index.ts
https://github.com/aptible/app-ui/assets/1940365/e243dbf7-6ae1-45a0-bb54-67d2eb18241d
https://github.com/aptible/app-ui/assets/1940365/c91f80ee-b21c-471b-b33f-42c30bffb05b
> db backup mgmt

- src/deploy/endpoint/index.ts
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/endpoint-detail-settings.tsx
- src/ui/pages/endpoint-detail.tsx
- src/ui/shared/button.tsx
- src/ui/shared/endpoint/index.tsx
https://github.com/aptible/app-ui/assets/1940365/1406435d-6e8c-489e-a18c-33d2763431f0
> refactor: endpoint delete confirmation

- src/app/test/create-db.test.tsx
- src/deploy/environment/index.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/test/index.tsx
- src/ui/pages/backup-restore.tsx
- src/ui/pages/environment-detail-settings.test.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/db/creator-form.tsx
- src/validator/index.ts
feat: change name for environment
> feat: deprovision environment

- src/app/router.tsx
- src/deploy/certificate/index.ts
- src/deploy/endpoint/index.ts
- src/routes/index.ts
- src/ui/layouts/cert-detail-layout.tsx
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/layouts/index.ts
- src/ui/pages/cert-detail-apps.tsx
- src/ui/pages/cert-detail-endpoints.tsx
- src/ui/pages/cert-detail-settings.tsx
- src/ui/pages/cert-detail.tsx
- src/ui/pages/environment-detail-certificates.tsx
- src/ui/pages/index.ts
- src/ui/shared/app/app-list.tsx
- src/ui/shared/app/endpoints-detail.tsx
- src/ui/shared/cert.tsx
- src/ui/shared/endpoints-overview.tsx
- src/ui/shared/index.ts
- src/ui/shared/pill.tsx
feat: cert delete
https://github.com/aptible/app-ui/assets/1940365/bdff59a0-d43f-4f64-9c0c-a26027dc6562
https://github.com/aptible/app-ui/assets/1940365/3544d30a-f538-4d24-8a58-64994156bd47
> feat: cert detail

- src/ui/shared/db/backup-list.tsx
Add # of results for Backup Tables
> Add Counts to Backups Table

- src/ui/pages/db-detail-scale.tsx
doing this temporarily to buy time while i get unit tests / other bits (moved some to selectors) ready. currently this unfortunately messes with memory in the current price when shifting things around
> chore: fix scaling estimates

- src/app/router.tsx
- src/deploy/certificate/index.ts
- src/deploy/endpoint/index.ts
- src/routes/index.ts
- src/ui/pages/app-create-endpoint.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/environment-detail-certificates.tsx
- src/ui/pages/environment-detail-create-cert.tsx
- src/ui/pages/index.ts
> feat: create cert for env

- src/deploy/activity/index.ts
- src/deploy/operation/index.ts
- src/types/deploy.ts
should look like this:
currently:
> chore: missed disk size for db resizes

- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/app-detail-service-metrics.tsx
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/db-detail-metrics.tsx
- src/ui/pages/db-detail-scale.tsx
- src/ui/shared/resource-group-box.tsx
Small design tweaks
BEFORE - Too much space below Save Buttons
AFTER - Less Space Below Save Buttons
---
BEFORE - DB Type not Capitalized
AFTER -  DB Type is Capitalized
---
BEFORE - Pills missing gap spacing in bewteen
AFTER - Added spacing
---
BEFORE - Missing Period at end of tooltip
AFTER
> Small Design Tweaks

- src/ui/shared/environment/backup-retention-policy-view.tsx
Make backup policy form responsive
> Make-backup-policy-form-responsive

- src/ui/pages/create-metric-drain.tsx
Edit Create Metric Drain
BEFORE
AFTER
> Edit create metric drain

- src/deploy/database/index.ts
- src/deploy/service/index.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/db-detail-scale.tsx
> fix: corrected profile selection not persisting on update

- src/deploy/environment/index.ts
- src/ui/shared/environment/environment-list.tsx
> feat: create env buttons

- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/backup-restore.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/endpoints-detail.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
**Add Missing Variant to New Endpoint button**
BEFORE
AFTER
**Move Database Endpoints tab to 3rd spot in priority**
BEFORE
AFTER
Add Scale button to Databases index & Change Logs color
AFTER
Add more clarity to Cloning DBs from Backups
BEFORE
AFTER
> Design-Tweaks-jc

- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/backup-restore.tsx
- src/ui/pages/db-detail-backups.tsx
**Edit Backup Policy Button Label**
BEFORE
AFTER
**Change CPU Limits to say Isolation**
BEFORE
AFTER
**Add more clarity to Clone form**
BEFORE
AFTER
> Bug-Fixes-jc

- src/ui/pages/backup-restore.tsx
- src/ui/shared/db/backup-list.tsx
**Add more clarity to Clone form**
BEFORE
AFTER
> Design Tweaks

- src/ui/pages/db-create-endpoint.test.tsx
- src/ui/pages/db-create-endpoint.tsx
Tweak banner message & style
BEFORE
AFTER - Remove Deploy references
> database-endpoint-banner-edits-jc

- src/ui/shared/activity.tsx
dropped needless prefetching (now done with bootup) @neurosnap
> chore: no need to refetch these

- src/app/test/create-metric-drain.test.tsx
- src/ui/pages/create-metric-drain.tsx
> Change Org Name Label

- src/app/test/create-log-drain.test.tsx
- src/app/test/org-picker.test.tsx
- src/deploy/database/index.ts
- src/deploy/log-drain/index.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/ui/pages/create-log-drain.tsx
- src/ui/pages/create-metric-drain.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/environment-detail-integrations.tsx
- src/ui/pages/org-picker.tsx
- src/ui/shared/code.tsx
- src/ui/shared/db/selector.tsx
- src/ui/shared/index.ts
- src/ui/shared/org-picker.tsx
> feat: log drain creation forms

- src/ui/pages/environment-detail-settings.tsx
Improve readability of content
BEFORE
AFTER
> design-tweak-banner

- src/ui/shared/application-sidebar.tsx
- src/ui/shared/input.tsx
Small tweaks to save space on the sidebar and above tables
> Save Space Tweaks

- src/deploy/stack/index.ts
- src/routes/index.ts
- src/ui/pages/create-project-git.tsx
- src/ui/pages/create-project-name.tsx
- src/ui/shared/environment/environment-list.tsx
fix: preselect stack when creating environment
> fix: use `stack.default` to find default stack

- src/ui/pages/create-project-git-settings.tsx
- src/ui/pages/create-project-git-status.test.tsx
- src/ui/pages/create-project-git.tsx
Design Tweaks:
• Capitalize ID
• Shorten text and tweak text styles
• Make Buttons the correct size
> Design tweaks jc

- src/app/test/create-endpoint.test.tsx
- src/deploy/certificate/index.ts
- src/deploy/endpoint/index.ts
- src/ui/pages/app-create-endpoint.test.tsx
- src/ui/pages/app-create-endpoint.tsx
> fix(endpoint): create endpoint conditional form inputs

- src/deploy/database-images/index.ts
- src/mocks/data.ts
- src/ui/shared/db/creator-form.tsx
fix: properly sort `dbImage.description` descending alphanumeric
> fix: use `dbImage.description` for select label

- src/ui/shared/db/backup-list.tsx
Add confirm button when deleting backups always
> add-confirm-button-to-delete-backups

- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/db-detail-scale.tsx
**Style Database and Service Scale Forms**
• Shorten Disk Size description
• Tweak spacing & text styles to improve readability
BEFORE
AFTER
> scale-form-styling

- src/deploy/database/index.ts
- src/types/deploy.ts
- src/ui/pages/create-db.tsx
- src/ui/pages/create-project-git-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/shared/db/creator-form.tsx
https://app.shortcut.com/aptible/story/17406/allow-databases-to-be-individually-excluded-from-backup-policies
@neurosnap I'm a veeeeeery green FE hack, would appreciate you looking at this PR with skepticism 🙏
> Database backup exclusion

- src/ui/pages/db-detail-settings.tsx
> change-text-jc

- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
> refactor: no last operation column for apps/dbs index views

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/op-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/shared/detail-page-header-view.tsx
Make header cards more responsive
BEFORE
AFTER
> header-card-tweak

- src/ui/pages/create-log-drain.tsx
> feat(log-drain): display BAA notice info by drain type

- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/environment/index.ts
- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/environment-detail-settings.tsx
Show Saved Message Banner for form updates:
> add-banner-messages

- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
Works on the Endpoints Detail page, **I didn't test on the All Endpoints page**
> copy-endpoints

- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/environment/environment-list.tsx
**This is a simpler PR without the copy functionality 👍 we can do that later**
> show-IDs-simpler-jc

- index.css
- package.json
- src/app/packages.ts
- src/billing/index.ts
- src/deploy/plan/index.ts
- src/env/index.ts
- src/initial-data/index.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/organizations/index.ts
- src/types/state.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-payment-required.ts
- src/ui/layouts/auth-required.tsx
- src/ui/layouts/hero-bg-layout.tsx
- src/ui/pages/billing-method.tsx
- src/ui/pages/plans.test.tsx
- src/ui/pages/plans.tsx
- src/ui/shared/plan.tsx
- src/vite.d.ts
- yarn.lock
> Payment takeover screen

- src/ui/layouts/app-detail-layout.tsx
- src/ui/shared/copy.tsx
- src/ui/shared/index.ts
https://github.com/aptible/app-ui/assets/1940365/f610b743-ffa9-4296-89a1-49cdf85bf24b
> feat: <CopyText /> component

- src/ui/pages/billing-method.tsx
> Billing form design tweaks

- index.css
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/copy.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/pre-code.tsx
- src/ui/shared/tooltip.tsx
feat(tooltip): added `variant=left` to `<Tooltip />`
> refactor: use `<CopyText />` for all copy buttons

- src/ui/pages/app-detail-settings.tsx
> text-tweak-jc

- src/ui/shared/environment/environment-list.tsx
> fix: remove "Last Deployed" column on env list

- src/ui/pages/app-detail-service-metrics.tsx
- src/ui/pages/db-detail-metrics.tsx
Center Loader Spinner on Metrics tabs
> center-loader-spinner

- src/ui/shared/db/database-list.tsx
Add Disk Size to Databases Table
AFTER
> add-disk-size-to-dbs-table

- src/deploy/image/index.ts
- src/ui/layouts/app-detail-layout.tsx
> App header show git docker info

- src/ui/pages/app-detail-settings.tsx
- src/ui/shared/pre-code.tsx
https://github.com/aptible/app-ui/assets/1940365/bb7f158b-4004-4444-bb6c-2a828d66ace7
> feat(app): show env vars in settings tab

- src/ui/shared/footer.tsx
> feat update footer links

- src/deploy/stack/index.ts
- src/ui/pages/create-project-name.tsx
> fix(ftux): ensure valid default stack selected

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
After deprovisioning apps and databases go to the Environment / Activity tab
> feat change redirect urls after deprovisioning apps and databases

- src/app/router.tsx
- src/deploy/stack/index.ts
- src/routes/index.ts
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/index.ts
- src/ui/pages/stack-detail-hids.tsx
- src/ui/shared/table.tsx
https://github.com/aptible/app-ui/assets/1940365/576a6438-facb-47c8-ad25-5350e10d5299
> feat(stack): managed hids tab

- src/ui/pages/app-detail-settings.tsx
Fix "How to Deploy Changes" view docs link so it goes to our All deployment guides doc, so users can:
• Read how to migrate to direct docker deploy
• Set up CI/CD
• Etc...
> fix(app):change how to deploy changes view docs link

- src/app/router.tsx
- src/deploy/configuration/index.ts
- src/deploy/permission/index.ts
- src/deploy/permission/selectors.test.ts
- src/projects/index.ts
- src/routes/index.ts
- src/string-utils/index.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-env-editor.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/pages/app-detail-config.tsx
- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/create-project-git-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/index.ts
- src/ui/pages/stack-detail-vpc-peering.tsx
- src/ui/pages/stack-detail-vpn-tunnels.tsx
- src/ui/shared/app/config.tsx
- src/ui/shared/app/index.ts
- src/ui/shared/button.tsx
- src/ui/shared/detail-page-header-view.tsx
- src/ui/shared/secret.tsx
There's a bunch of code changes that are mostly moving code around.
https://github.com/aptible/app-ui/assets/1940365/8e4856ad-dc6e-4c79-8342-79b3eaf4154b
> feat(app): edit env vars

- src/ui/pages/app-detail-config.tsx
> fix(app): add icon to edit env vars button

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/db-detail-settings.tsx
- src/ui/pages/stack-detail-vpc-peering.tsx
- src/ui/pages/stack-detail-vpn-tunnels.tsx
- src/ui/shared/button.tsx
> fix(app):fix view docs button placement

- src/app/router.tsx
- src/routes/index.ts
- src/ui/pages/create-stack.tsx
- src/ui/pages/index.ts
- src/ui/pages/stacks.tsx
- src/ui/shared/input.tsx
> feat(stack): request dedicated stack form

- src/deploy/support/index.ts
> Style(app) change success banner message

- src/ui/pages/create-stack.tsx
- src/ui/pages/support.tsx
chore(stack): add real terms and conditions link
> chore(stack): add "other" option to requesting stack

- src/ui/pages/environment-detail-backups.tsx
Add banner to environment backups
> feat(app): add banner to environment backups

- src/ui/shared/db/database-list.tsx
Add Container Size Column to DBs list
> feat(app): add container size column to database list

- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/endpoint-detail-setup.tsx
> chore(endpoint): always show ACME configure tab 

- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/create-stack.tsx
**Fix Service Process typo**
BEFORE
AFTER
**Add more space between button and checkbox**
> fix(app): fix typo

- src/deploy/app/index.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/pages/app-detail-config.tsx
- src/ui/shared/log-viewer.tsx
- src/ui/shared/pre-code.tsx
> App config scan info

- src/deploy/endpoint/index.ts
- src/ui/shared/endpoint/endpoint-list.tsx
See: https://aptible.sentry.io/issues/4506400195/?project=4504990894391296&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d&stream_index=1
> fix(endpoints): external_host from api can be null

- src/ui/pages/create-stack.tsx
- src/ui/pages/stacks.tsx
Changes
Change button text
Add price callout
> style(app): dedicated stacks changes

- src/ui/pages/create-stack.tsx
https://aptible.slack.com/archives/C022BUSF0B1/p1695996268527139?thread_ts=1695782675.139309&cid=C022BUSF0B1
> Create stack restrict access by user's current plan

- src/ui/pages/environment-detail-certificates.tsx
> fix(environments): always show "New Certificate" button

- src/ui/pages/create-project-name.tsx
- src/ui/pages/create-stack.tsx
- src/validator/index.ts
https://aptible.slack.com/archives/C022BUSF0B1/p1696259870223359
New regex:
```ts
new RegExp(/^[0-9a-z-]{1,26}$/);
```
> fix(stack): create stack use correct validator

- src/app/router.tsx
- src/ui/layouts/app-sidebar-layout.tsx
- src/ui/layouts/index.ts
- src/ui/layouts/settings.tsx
- src/ui/pages/settings.tsx
- src/ui/shared/footer.tsx
- src/ui/shared/settings-sidebar.tsx
> style(settings): settings layout

- src/ui/layouts/settings.tsx
- src/ui/pages/otp-setup.tsx
- src/ui/pages/security-settings.tsx
- src/ui/shared/footer.tsx
- src/ui/shared/settings-sidebar.tsx
- src/ui/shared/settings/team-list-view.tsx
- src/ui/shared/status-box.tsx
- src/validator/index.ts
Style Settings pages & make responsive
> style(app): design changes to settings, footer and explainer text

- src/app/test/no-payment-found.test.tsx
- src/app/test/org-picker.test.tsx
- src/deploy/plan/index.ts
- src/types/state.ts
- src/ui/layouts/auth-required.tsx
- src/ui/pages/logout.test.tsx
- src/ui/pages/plans.test.tsx
- src/ui/pages/plans.tsx
- src/ui/shared/plan.tsx
> refactor(plans): internal restructure

- src/ui/pages/create-project-git.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/app/endpoint-selector.tsx
- src/ui/shared/code.tsx
- src/ui/shared/how-it-works-footer.tsx
**Changes**
• Style code component — Decrease font-size, adjust spacing, round corners
• Use code component in our pages
BEFORE
AFTER
> Style(app): style code component

- src/app/tuna.tsx
- src/auth/signup.ts
- src/auth/token.ts
- src/tuna/index.ts
- src/ui/pages/create-project.tsx
- src/ui/shared/feedback.tsx
feat(auth): added tuna events for login/signup
> refactor(tuna): formalized tuna methods

- src/auth/loader.ts
https://aptible.sentry.io/issues/4523886519/?alert_rule_id=14705789&alert_type=issue&notification_uuid=87e7a41e-a8dc-4759-8b6b-dce67193ccbe&project=4504990894391296&referrer=slack
> fix(login): exception_context undefined

- src/ui/pages/styles.tsx
> Fix: fix styles page so it renders

- src/ui/layouts/settings.tsx
- src/ui/pages/security-settings.tsx
- src/ui/shared/settings-sidebar.tsx
>  style: settings page

- src/ui/pages/billing-method.tsx
- src/ui/pages/signup.tsx
**Fix cookie banner bug on sign up** 
• Banner shows below content
BEFORE
AFTER
---
**Make info panel always fit viewport height**
BEFORE
AFTER
> Fix cookie banner on sign up page

- src/ui/pages/add-security-key.tsx
- src/ui/pages/otp-recovery-codes.tsx
- src/ui/pages/otp-setup.tsx
- src/ui/pages/security-settings.tsx
**Style more settings pages**
• 2FA
• Recovery Codes
• Security Keys
**Added breadcrumbs and container boxes to all pages**
> style: settings 2fa, recovery codes, and security keys pages

- src/ui/pages/plans.tsx
- src/ui/shared/app/services-detail.tsx
**Changes**
• Update choose a plan text to accommodate in-trail users
• bold service names more to help them standout and improve readability
BEFORE
AFTER
BEFORE
AFTER
> style: design tweaks

- src/bootup/index.ts
- src/ui/pages/elevate.tsx
- src/ui/shared/how-it-works-footer.tsx
Users are getting confused why they are being redirected to what looks like a login page after they have already authenticated.
This explainer text hopefully prevents the user from being confused and submitting a bug report.
> chore(elevate): add explainer text

- src/auth/organization.ts
- https://aptible.sentry.io/issues/4538698949/?alert_rule_id=14705789&alert_type=issue&notification_uuid=d425c663-2ca1-4057-9f81-f2f83765c76c&project=4504990894391296&referrer=slack
- https://aptible.sentry.io/issues/4532872429/?referrer=slack&notification_uuid=fe749127-aa13-4ae6-91bf-4d54fcfe92e1&alert_rule_id=14705789&alert_type=issue
> fix(orgs): ensure we have orgs before accessing array

- src/ui/pages/create-project-git-settings.tsx
- src/ui/pages/create-project-git.tsx
- src/ui/shared/how-it-works-footer.tsx
Change accordion closed style
---
---
> style: change accordion closed style

- src/deploy/backup/index.ts
- src/ui/pages/db-detail-backups.tsx
- src/ui/shared/db/backup-list.tsx
> style(backups): show if backup was copied from another backup

- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/stacks.tsx
Add memory limit status to Stacks table and Stack detail header 
AFTER
> style: add memory limits to stacks

- src/ui/pages/support.tsx
Forgot to add setViewedSuggestion to true. Oops
> add setViewedSuggestion

- src/deploy/certificate/index.ts
- src/deploy/endpoint/index.ts
- src/mocks/handlers.ts
- src/types/deploy.ts
- src/ui/pages/app-create-endpoint.tsx
- src/ui/pages/endpoint-detail-settings.test.tsx
- src/ui/pages/endpoint-detail-settings.tsx
- src/ui/shared/cert-selector.tsx
- src/ui/shared/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1696735387866269
> feat(endpoint): edit certificate

- src/database/index.ts
- src/deploy/database/index.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/shared/db/database-list.tsx
added image version to database detail/list per: https://www.notion.so/aptible/App-UI-Bugs-Ideas-a386eb0d325d410a93717c6d91de0466?pvs=4#37a73d152ebc4fa0a69984f18ce7a297
> add db image version to details

- src/ui/pages/sso-token-cli.tsx
> fix(sso-cli): if token is empty, inform user and let them refetch token

- src/app/router.tsx
- src/deploy/database-credential/connection-url-rewrite.test.ts
- src/deploy/database-credential/index.ts
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/routes/index.ts
- src/types/deploy.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/pages/db-detail-creds.tsx
- src/ui/pages/endpoint-detail-credential.tsx
- src/ui/pages/index.ts
- src/ui/shared/db/credential.tsx
- src/ui/shared/db/index.ts
> feat(endpoint): authenticated endpoint URL tab

- src/deploy/code-scan-result/index.ts
- src/token/jwt-parser.ts
- src/ui/pages/app-detail-config.tsx
- src/ui/pages/create-project-git-settings.tsx
https://aptible.sentry.io/issues/4545302452/?project=4504990894391296&query=&referrer=project-issue-stream
https://aptible.sentry.io/issues/4551122548/?project=4504990894391296&query=&referrer=project-issue-stream
> Fix code scan error

- src/app/test/org-picker.test.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/user-menu.tsx
Fix icon title tags so they match their concepts
AFTER
> fix:icon-title-tags

- src/string-utils/index.ts
- src/string-utils/parse-text.test.ts
- src/ui/pages/app-deploy-configure.tsx
- src/ui/pages/app-detail-config.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1697559175356709
> fix(app): editing config support multiline env vars

- src/ui/layouts/stack-detail-layout.tsx
https://github.com/aptible/app-ui/assets/4295811/889088ae-e448-4d33-af36-aca1844a62a8
> style:add-outbound-ip-address-tooltip

- src/ui/pages/app-deploy-with-git.tsx
TODO
**• Make the default selected option be Custom Code so the extra step shows**
> style:add database migration info to push your code step

- src/ui/shared/activity.tsx
- src/ui/shared/db/database-list.tsx
Vertically center align text for database list and activity list
• reduce margin-top 
BEFORE
.
AFTER
.
> style: vertically center align text

- src/api/index.ts
- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/deploy/endpoint/index.ts
- src/deploy/environment/index.ts
- src/deploy/log-drain/index.ts
- src/deploy/metric-drain/index.ts
- src/deploy/service/index.ts
- src/deploy/stack/index.ts
- src/ui/pages/support.tsx
This change will help us properly remove stale data from our local store by first resetting the store when we fetch all data from the API successfully.
> fix: wipe local data when fetching all pages from api

- src/ui/shared/app/services-detail.tsx
> fix: services button spacing

- src/ui/pages/settings-profile.tsx
- src/ui/pages/settings-ssh.tsx
Style settings breadcrumbs to match our pattern
• change font size
BEFORE
AFTER
> style: style settings breadcrumbs

- src/ui/pages/environment-detail-integrations.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/db/database-list.tsx
Small table alignment fixes
Databases table
- align actions column label right
Activity table empty view
- span all columns
Both drains table
- align actions column label right
> style: table alignment fixes

- src/ui/pages/settings-team-members.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
Change the placeholder text from `Search ...` to match the existing pattern of `Search...`
• remove the extra space
> style: search placeholder text

- src/app/test/no-payment-found.test.tsx
- src/ui/pages/plans.tsx
- src/ui/shared/plan.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1697640529400629
> fix(plans): dont let user change plans without CC

- src/deploy/app/index.ts
- src/deploy/database/index.ts
- src/ui/shared/activity.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1698955439076489
> fix: only poll for service operations on app/db activity pages

- src/deploy/database/index.ts
https://aptible.sentry.io/issues/4597016680/?alert_rule_id=14705789&alert_type=issue&notification_uuid=2d0a5421-10dd-4226-907c-32169a883cd7&project=4504990894391296&referrer=slack
> fix(db): rm erroneous next() call

- src/ui/pages/environment-detail-backups.tsx
> style: backup banner copy change

- src/ui/shared/app/services-detail.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
https://aptible.slack.com/archives/C05EV1X217Y/p1699294766584009
> fix(app): endpoint list: display external host and service process type

- src/validator/index.ts
- src/validator/ip-validator.test.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1699375537031199?thread_ts=1697237599.861249&cid=C05CMUW3LHX
> fix(endpoint): rm cidr validation max length

- src/ui/pages/get-started.tsx
- src/ui/pages/signup.tsx
> style: signup page copy edits

- src/bootup/index.ts
- src/fx/index.ts
- src/mocks/handlers.ts
- src/system-status/index.ts
- src/ui/shared/application-sidebar.tsx
> feat: system status indicator

- src/ui/pages/settings-team-members.tsx
- src/ui/shared/csv.tsx
- src/ui/shared/index.ts
Exports:
- id
- name
- email
- verified
- 2fa
> feat(settings.members): CSV download of list

- src/ui/pages/settings-team-members.tsx
**Members tables tweaks**
• Rename User column to Name (matches csv download and is more descriptive)
• Make email be its own column to reduce row height
• Make Names darker to improve readability
> style: members table

- src/deploy/service/index.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/stack-detail-hids.tsx
- src/ui/shared/table.tsx
Adds advanced settings fold to customize the policy at will
Will be rebased once https://github.com/aptible/app-ui/pull/563 is in.
> Allow updates to autoscaling policy

- src/ui/shared/select.tsx
> style: remove unnecessary class

- src/deploy/endpoint/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1700410066259359
> fix(cert): we were using the wrong loader id when handling cert errors

- src/auth/organization.ts
- src/mocks/handlers.ts
- src/organizations/index.ts
- src/types/state.ts
- src/ui/pages/settings-team-contacts.test.tsx
- src/ui/pages/settings-team-contacts.tsx
- src/ui/shared/settings-sidebar.tsx
> feat: team settings contacts form

- src/deploy/service/index.ts
See: https://aptible.sentry.io/issues/4655799860/?referrer=slack&notification_uuid=0bf32406-1393-4c11-9fe7-dfdb6f733b26&alert_rule_id=14705789&alert_type=issue
> fix(app.scale): prevent container size from being set to null

- src/api/index.ts
- src/auth/index.ts
- src/auth/organization.ts
- src/auth/saml.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/ui/pages/settings-team-sso.test.tsx
- src/ui/pages/settings-team-sso.tsx
- src/ui/shared/settings-sidebar.tsx
- src/users/selectors.ts
> feat: team settings sso

- src/deploy/app/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1701211692041179
> fix: app name change shows incorrect banner when err

- src/ui/pages/endpoint-detail-settings.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1701217982768259
> fix(endpoint): correctly preselect existing cert

- src/auth/token.ts
Don't redirect to login when it fails
https://aptible.slack.com/archives/C05DFHDSF2S/p1701204975023829
> fix(impersonate): check for http response error

- src/deploy/service/index.ts
Adds a message into the loader banner on success and error
> Show success and error messages for autoscaling services policies

- src/deploy/backup/index.ts
- src/types/deploy.ts
- src/ui/pages/environment-detail-backups.tsx
- src/ui/shared/db/backup-list.tsx
design(environment.backups): show if backup is final
> fix(environment.backups): correctly show db name

- src/app/router.tsx
- src/app/test/app-detail-service-scale.test.tsx
- src/ui/layouts/index.ts
- src/ui/layouts/service-detail-layout.tsx
> feat: service detail header

- src/roles/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1701794183231169
> fix(settings): only allow invitation into specific roles

- src/app/router.tsx
- src/mfa/index.ts
- src/routes/index.ts
- src/ui/pages/index.ts
- src/ui/pages/otp-reset-verify.tsx
- src/ui/pages/settings-team-members-edit.tsx
- src/ui/shared/button.tsx
> feat(settings.team): admin otp reset ability

- src/organizations/index.ts
- src/users/effects.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1701783049752519
> fix(user.selected_org): only set org if it is present in store

- src/deploy/backup-retention-policy/index.ts
- src/types/deploy.ts
- src/ui/pages/environment-detail-backups.test.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/environment/backup-retention-policy-view.tsx
- src/ui/shared/index.ts
- src/ui/shared/key-value.tsx
Related: https://github.com/aptible/deploy-api/pull/1311
https://aptible.slack.com/archives/C05EV1X217Y/p1701818377496589
> feat(backup_retention_policy): support for setting yearly policy

- src/ui/shared/app/services-detail.tsx
Add a icon to indicate column is sortable
https://github.com/aptible/app-ui/assets/4295811/91399447-dcc5-4727-999d-7839f1b1c54d
> style: add sorting arrow indicators

- src/ui/hooks/use-trial-notice.ts
https://aptible.sentry.io/issues/4711414707/?alert_rule_id=14705789&alert_type=issue&notification_uuid=8fa232dc-77cd-4ad1-a200-2545eedaaea8&project=4504990894391296&referrer=slack
> fix: no trials on embedded object

- src/ui/hooks/use-env-ops-poller.ts
- src/ui/hooks/use-poller.ts
- src/ui/hooks/use-visibility.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1701384256834089
> perf: disable running pollers when tab is inactive

- src/bootup/index.ts
- src/ui/pages/org-picker.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1702492487452239
> fix(org.picker): refetch data when switching orgs

- src/app/test/org-picker.test.tsx
- src/ui/pages/org-picker.tsx
- src/users/effects.ts
fix(org): reauthed orgs need to use SSO to login
https://aptible.slack.com/archives/C05CMUW3LHX/p1702504324049259
> fix(org): only set org if it doesnt need reauthed

- src/ui/shared/app/services-detail.tsx
**Changes**
• Add metrics button to the App Detail / Service Tab
> fix: add metrics button to the App Detail / Service Tab

- src/ui/pages/team-accept-invite.tsx
Make accept invite button stand out more
BEFORE
AFTER
> style: make accept invite button larger

- src/ui/layouts/environment-detail-layout.tsx
- src/ui/pages/styles.tsx
Remove last deployed from environment header
BEFORE
AFTER
> style: remove last deployed from environment header

- src/date/index.ts
- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/operation-detail-layout.tsx
- src/ui/pages/environment-detail-integrations.tsx
- src/ui/shared/activity.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/container-metrics-chart.tsx
- src/ui/shared/db/backup-list.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/operation-list-row.tsx
**Global Change** 
• Change GMT to UTC
**BEFORE**
---
**AFTER**
> style: change GMT to UTC time format

- src/deploy/app/utils.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1704233964423339
> fix(service): metrics ignore services with 0 containers

- src/ui/pages/app-deploy-configure.tsx
We were trying to be clever with adding existing databases to the new db list and it was causing a bunch of hard-to-debug edge cases.
I believe this was to prevent the following scenario:
- User creates a database but `provision` fails (e.g. rate limit)
- User fixes rate limit and returns to ftux
- We no longer try to provision the db
For now, I think this is an edge case we can be okay with considering the error prone solution we had lingering the codebase.
> refactor(ftux): dont fill new dbs with existing

- src/ui/shared/app/app-list.tsx
This snuck into `main` on accident from me testing different strategies.
> fix(app): table loader

- src/ui/pages/app-create-endpoint.tsx
Change `Deploy will deliver...` to `Aptible will deliver...`
BEFORE
AFTER
> Fix: remove reference to Deploy

- src/ui/hooks/use-trial-notice.ts
https://aptible.sentry.io/issues/4834910999/?project=4504990894391296&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=inbox&stream_index=2
> fix: trial notice guard against undefined

- src/api/index.ts
- src/auth/index.ts
- src/auth/otp.ts
- src/auth/pass.ts
- src/auth/token.ts
- src/auth/webauthn.ts
- src/mfa/index.ts
- src/ui/pages/settings-otp-setup.tsx
- src/ui/pages/settings-security.tsx
- src/users/effects.ts
- Changing password
- Updating MFA
https://aptible.slack.com/archives/C05CMUW3LHX/p1705072039725959?thread_ts=1704815260.518129&cid=C05CMUW3LHX
> chore(security): revoke other tokens for some ops

- src/date/index.ts
- src/ui/layouts/app-sidebar-layout.tsx
- src/ui/pages/sso.tsx
- src/ui/shared/application-sidebar.tsx
- src/ui/shared/index.ts
- src/ui/shared/org-sso-required.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1705011270434519
> chore: show banner for sso required orgs

- src/app/test/role-mgmt.test.tsx
- src/deploy/permission/index.ts
- src/mocks/data.ts
- src/ui/pages/role-detail-environments.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1705596248120459
TODO:
> fix(role): filter permissions by account AND role

- src/deploy/permission/index.ts
- src/ui/pages/role-detail-environments.tsx
- src/ui/shared/banner.tsx
style(role): more minimal banner status when updating perm
> fix(role): ability to uncheck basic_read

- src/ui/pages/support.tsx
Allows a user to be un-authenicated on app-ui and still submit a ticket
> Anonymous support form

- src/ui/pages/org-picker.tsx
Show Org ID on Org Picker 
https://github.com/aptible/app-ui/assets/4295811/88604d05-7ab1-4682-82e0-d55daad0e670
> feat: show org id on org picker

- src/bootup/index.ts
There are two processes that can set the organization selected within the UI: 1) fetching organizations and 2) fetching the current user
We want to make sure those two operations complete before fetching organization related data.
> refactor: fetch org then user then billing

- src/ui/pages/app-detail-service-scale.tsx
[slack](https://aptible.slack.com/archives/C0613V9E1PD/p1706645796644869)
> [chore] Update min value for min and max autoscale container size

- src/ui/hooks/use-users-for-role.ts
https://aptible.sentry.io/issues/4931370388/?alert_rule_id=14705789&alert_type=issue&notification_uuid=f22f5c51-a694-40e0-85a1-9bd304336f46&project=4504990894391296&referrer=slack
> fix(role): ensure we have embedded data from request

- src/ui/pages/support.tsx
- To get the email validation on the email form input for unauthenticated submissions.
> fix support email form type

- src/ui/pages/support.tsx
Remove extra margin-top code
BEFORE
AFTER
> chore: fix support page margin

- src/ui/pages/app-detail-config.tsx
- src/ui/shared/pre-code.tsx
`pre` tag doesn't behave the width of its parent so we need to set a max width on it.
> style: set max width on pre tag

- src/app/store.ts
- src/auth/token.test.ts
- src/auth/token.ts
- src/test/index.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1707462063586959
> fix(settings): use elevated token when revoking all tokens

- src/deploy/endpoint/endpoint.test.ts
- src/deploy/endpoint/index.ts
- src/ui/layouts/endpoint-detail-layout.tsx
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/pages/app-deploy-status.tsx
- src/ui/shared/endpoint/endpoint-list.tsx
- src/ui/shared/endpoint/util.test.tsx
- src/ui/shared/endpoint/util.tsx
- src/ui/shared/resource-group-box.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1706829801698329
https://github.com/aptible/deploy-ui/blob/9ed4b5de1a3789e7fe1701050c5ba28a1662d6bd/app/models/vhost.js#L39
> fix(endpoint): use same logic as `deploy-ui`

- src/deploy/activity-report/index.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-paginated-activity-reports.ts
- src/ui/pages/environment-detail-activity-reports.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1707767961532209
> feat(env): server side paginate activity reports

- src/ui/layouts/endpoint-detail-layout.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1706811491031179
> chore(endpoint): show ACME tab after endpoint is privisioned

- src/ui/pages/app-deploy-configure.tsx
- src/ui/pages/app-deploy-with-github.tsx
- src/ui/shared/progress-project.tsx
**Tighten spacing in FTUX header**
BEFORE
AFTER
---
Add clarity to Text
BEFORE
AFTER
---
Add Databases explainer text
BEFORE
AFTER
> chore: tighten spacing in FTUX header & tweak text

- src/deploy/stack/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/stack.tsx
Depends on: https://github.com/aptible/deploy-api/pull/1391
> feat(stack): show self_hosted stacks with aws account id

- src/ui/shared/environment/environment-list.tsx
Make databases column name plural
BEFORE
AFTER
> chore: make databases column name plural

- src/deploy/backup/index.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1709821710003649
> fix(backup): pass `page` to fetch request

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/database-detail-layout.tsx
Add Created Date to App and Database headers
> feat: add created date to app and database headers

- src/ui/pages/role-detail-members.test.tsx
- src/ui/pages/role-detail-members.tsx
- src/ui/shared/button.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1711380419919769
- added an invite by email from the role page using the logic @neurosnap suggested.
Testing:
- so far I only have tested manually and confirmed an invited user only gets the selected role.
- Todo: add automated testing.
Approvals
@neurosnap and @joshuaj194 for functionality, @joeclayallday for design
Role page for role admins:
> Sc 23131 invite role admin

- src/roles/index.ts
- src/types/auth.ts
- src/users/selectors.ts
chore(team): sort users alphabetically
> chore(team): ignore compliance roles in table

- src/ui/pages/styles.tsx
- src/ui/shared/icons.tsx
> feat: add more icons

- src/ui/pages/styles.tsx
- src/ui/shared/icons.tsx
> feat: add new icon

- src/ui/pages/__snapshots__/app-detail-deployments.test.tsx.snap
- src/ui/pages/app-detail-deployments.test.tsx
- src/ui/pages/sources.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/git.tsx
- src/ui/shared/icons.tsx
Add Commit icon
Update Sources tooltip description
> feat: add commit icon

- src/ui/shared/icons.tsx
> fix: update circle check icon

- package.json
- src/ui/pages/__snapshots__/app-detail-deployments.test.tsx.snap
- src/ui/pages/environment-detail-certificates.tsx
- src/ui/pages/environment-detail-integrations.tsx
- src/ui/pages/role-detail-environments.tsx
- src/ui/pages/settings-team-members.tsx
- src/ui/pages/sources.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/container-metrics-chart.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/deployments-table.tsx
- src/ui/shared/environment/environment-list.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/pre-code.tsx
- src/ui/shared/resource-list-view.tsx
- src/ui/shared/tooltip.tsx
- yarn.lock
This PR refactors our `Tooltip` component to use [Floating UI](https://floating-ui.com/docs/react) for better performance and more robust handling of automatic placement.
For the most part, this change won't impact the user experience. This PR is laying groundwork for adding more context-specific help/info in the future. However, it does add a couple of tooltips for Sources and Deployments, mostly for testing while developing.
> refactor: better tooltips

- src/ui/shared/log-viewer.tsx
https://aptible.sentry.io/issues/5236616978/?alert_rule_id=14705789&alert_type=issue&notification_uuid=56b5b0d2-d121-48b9-b2b4-c498be9818bc&project=4504990894391296&referrer=slack
> fix: handle when log viewer data is not a string

- src/ui/pages/app-detail-settings.tsx
- src/ui/pages/database-detail-settings.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/pages/settings-team-roles.tsx
- src/ui/shared/environment/index.ts
- src/ui/shared/environment/perms.tsx
- src/ui/shared/index.ts
- src/ui/shared/role.tsx
> feat(env): show permissions in settings tab

- src/ui/pages/settings-team-roles.tsx
- Empty permission check
- No users text-sm
> chore: role table cleanup

- src/ui/pages/settings-team-roles.tsx
This PR makes filters on the roles table sharable
> feat: filter roles table using url query params

- src/ui/layouts/operation-detail-layout.tsx
- src/ui/shared/activity.tsx
https://app.shortcut.com/aptible/story/24165/add-config-vars-to-activity-table?vc_group_by=day&ct_workflow=all&cf_workflow=500000186
> feat(activity): show env keys that changed for `app:configure`

- src/ui/pages/deployment-detail-logs.tsx
> chore(deployment): remove debug text from log viewer

- src/ui/pages/role-detail-members.tsx
- src/ui/pages/settings-team-members.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1714068997104849
> chore: change ref from MFA to 2FA

- src/deploy/database/index.ts
- src/mocks/handlers.ts
- src/ui/pages/database-detail-settings.test.tsx
- src/ui/pages/database-detail-settings.tsx
- Show validation errors
- Prevent user from submitting if there are replicas
- Show replicas
https://aptible.slack.com/archives/C05CMUW3LHX/p1714081944826279
> fix(db): dont let user deprovision if they have replicas

- src/deploy/configuration/index.ts
- src/deploy/operation/index.ts
- src/projects/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
https://aptible.sentry.io/issues/5284851457/?alert_rule_id=14705789&alert_type=issue&notification_uuid=97f4b852-7173-47d3-aaba-b9b1f2feead4&project=4504990894391296&referrer=slack
> fix(configuration): guard against null `configuration.env` obj

- src/ui/layouts/app-detail-layout.tsx
- src/ui/layouts/deployment-detail-layout.tsx
- src/ui/shared/application-sidebar.tsx
This PR removes the feature flag gating the Sources and Deployments feature.
> Remove the feature flag for Sources and Deployments

- src/app/packages.ts
- src/app/router.tsx
- src/app/test/role-mgmt.test.tsx
- src/deploy/permission/index.ts
- src/loaders/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/role-detail-environments.tsx
- src/ui/pages/settings-team-roles.tsx
- src/ui/shared/banner.tsx
- src/ui/shared/environment/perms.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/role.tsx
https://app.shortcut.com/aptible/story/24189/refactor-role-detail-environments-editor
https://github.com/aptible/app-ui/assets/1940365/5a0a6538-46c7-40f8-8f86-3df1804f015e
> refactor(role): env editor

- src/deploy/database/index.ts
https://app.shortcut.com/aptible/story/24921/warning-for-saved-changed-successfully
> fix(database): check for success before informing user

- src/ui/shared/operation-status.tsx
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
Addresses: https://aptible.sentry.io/issues/5573197224/?alert_rule_id=14705789&alert_type=issue&notification_uuid=78c2294a-8285-469b-b2aa-a55da98d7264&project=4504990894391296&referrer=slack
> refactor: array.prototype.at => array[len-1]

- src/deploy/app/index.ts
- src/ui/layouts/app-detail-layout.tsx
> fix(app): show deployment type and git remote

- src/projects/index.ts
Previously we were triggering an `app:configure` operation even when there were no values provided.
This change will only trigger a configure operation when there are values.
https://aptible.slack.com/archives/C071HPYMNSC/p1720648293509449
> fix(ftux): only create configure op if necessary

- src/ui/pages/sso-token-cli.tsx
[Slack context](https://aptible.slack.com/archives/C0237PYRF6D/p1720795819368849)
> Remove inaccurate promise about token revocation

- src/ui/hooks/use-trial-notice.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1720651421204469
> fix: inaccurate trial time left

- src/users/selectors.ts
https://aptible.slack.com/archives/C05CMUW3LHX/p1720716861886809
> fix: sort user list by name ascending

- src/ui/shared/environment/backup-retention-policy-view.tsx
https://aptible.slack.com/archives/C074W22RKC1/p1721067217501719?thread_ts=1720040136.116159&cid=C074W22RKC1
> Update backup retention policy reduction warning

- src/app/test/create-database.test.tsx
- src/deploy/app/utils.ts
- src/deploy/database/index.ts
- src/deploy/service/index.ts
- src/schema/factory.ts
- src/ui/hooks/index.ts
- src/ui/hooks/use-database-scaler.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/create-database.tsx
- src/ui/pages/database-detail-scale.tsx
- src/ui/pages/database-detail-settings.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/db/index.ts
- src/ui/shared/db/scale-options.tsx
- src/validator/index.ts
https://app.shortcut.com/aptible/story/25046/add-scaling-options-to-app-ui-when-creating-an-app-a-database-or-restoring-from-a-backup
> feat(db): scaling options on creation

- src/deploy/database-images/index.ts
- src/deploy/database/index.ts
- src/deploy/search/index.ts
Allows searching on the Database's image description.
> update search logic

- src/auth/signup.ts
- src/billing/index.ts
Requires https://github.com/aptible/auth-api/pull/593 before we can release this.
The linked auth change creates the records instead, so this would only throw errors. The errors don't block or anything, so the auth change can go first, but for keeping things clean, this would be nice to remove.
> Don't create billing records in UI

- src/ui/shared/db/scale-options.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1722549736411229
> chore(iops): provide more clear description text for iops limitations

- src/deploy/database-images/index.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/shared/db/database-eol-notice.tsx
Add an info banner for all databases running on EOL versions.
> Add Database EOL info banner

- src/ui/shared/db/database-eol-notice.tsx
> add changelog link to EOL banner

- src/ui/shared/db/database-eol-notice.tsx
> Update changelog link in EOL Banner

- src/api/index.ts
- src/bootup/index.ts
- src/deploy/backup/index.ts
- src/ui/pages/stack-detail-hids.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
Requires https://github.com/aptible/deploy-api/pull/1519. Fetches all backups on bootup in order to more accurately calculate monthly cost estimates.
> Fetch all backups

- src/deploy/backup/index.ts
- src/ui/hooks/use-paginate-backups.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/pages/environment-detail-settings.tsx
- src/ui/shared/db/database-list.tsx
https://app.shortcut.com/aptible/story/27112/inconsistent-data-with-estimated-costs-in-ui
> Add actions for fetching all pages of backups

- src/deploy/vpn-tunnel/index.ts
reference: https://aptible.slack.com/archives/C05CMUW3LHX/p1724155066488919
> chore(stack): fetch all vpn tunnels

- src/ui/pages/github-integration.tsx
**Design Tweaks**
• Float main add github account button to the left
• Float actions thead column right
• Float action buttons right
**BEFORE**
**AFTER**
> github-integration-styling

- src/app/test/app-detail-service-scale.test.tsx
- src/deploy/service-sizing-policy/index.ts
- src/deploy/stack/index.ts
- src/mocks/data.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/key-value.tsx
Depends on https://github.com/aptible/deploy-api/pull/1545 and https://github.com/aptible/deploy-api/pull/1549
> Add Horizontal Autoscaling

- src/ui/pages/app-detail-service-scale.tsx
https://aptible.sentry.io/issues/5941135719/?alert_rule_id=14705789&alert_type=issue&notification_uuid=5679e0f3-4282-43ea-b71b-bcbcf8d2a82e&project=4504990894391296&referrer=slack
> fix(app.scale): move return to after our hooks

- src/deploy/endpoint/index.ts
- src/types/deploy.ts
- src/ui/layouts/service-detail-layout.tsx
- src/ui/pages/app-create-endpoint.tsx
- src/ui/pages/app-deploy-status.tsx
> gRPC Endpoints

- src/ui/pages/endpoint-detail-setup.tsx
**Changes**
make check button larger on acme configure tab
> make check button larger on acme configure tab

- src/ui/pages/database-detail-backups.tsx
- src/ui/pages/endpoint-detail-setup.tsx
- src/ui/pages/environment-detail-backups.test.tsx
- src/ui/pages/environment-detail-backups.tsx
- src/ui/shared/environment/backup-retention-policy-view.tsx
> backup-pages-tweaks

- src/ui/shared/add-ssh-key.tsx
> Add extra step to ssh key instructions

- src/app/test/no-payment-found.test.tsx
- src/ui/pages/plans.test.tsx
- src/ui/shared/plan.tsx
> fix(plans): require confirmation before submitting

- src/billing/index.ts
- src/schema/factory.ts
- src/types/state.ts
- src/ui/pages/billing-method.tsx
https://aptible.slack.com/archives/C075NHZA76E/p1730472915120439
> fix(cc): preserve previous organization details json in billing detail

- src/app/test/database-detail-scale.test.tsx
- src/bootup/index.ts
- src/date/index.ts
- src/deploy/database/index.ts
- src/deploy/entities.ts
- src/deploy/index.ts
- src/deploy/manual_scale_recommendation/index.ts
- src/deploy/search/index.ts
- src/deploy/service-sizing-policy/index.ts
- src/schema/factory.ts
- src/schema/schema.ts
- src/types/state.ts
- src/ui/layouts/database-detail-layout.tsx
- src/ui/layouts/service-detail-layout.tsx
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/database-detail-scale.tsx
- src/ui/pages/styles.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/icons.tsx
- src/ui/shared/index.ts
- src/ui/shared/pill.tsx
- src/ui/shared/scale-recs.tsx
This feature is accessible only to the Aptible production organization.  This is so we can continue to QA scaling recommendations before GA.
> feat: manual scale recommendations

- src/deploy/database/index.ts
- src/deploy/operation/index.ts
- src/deploy/service/index.ts
- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/database-detail-scale.tsx
- src/ui/shared/scale-recs.tsx
- When clicking "Scale Up" or "Scale Down" in table views
- When "Apply Changes" + "Scale" is triggered
> feat(scale): tuna usage metric aggregation

- src/ui/shared/scale-recs.tsx
https://aptible.slack.com/archives/C0784CNF3MJ/p1731083850817479
> fix: no recommendation == right-sized

- src/deploy/database/index.ts
- src/deploy/operation/index.ts
- src/ui/shared/scale-recs.tsx
This will make it easier for us to use analytics.
> chore(scale-recs): add org info to tuna

- src/deploy/database/index.ts
- src/ui/pages/database-detail-settings.test.tsx
- src/ui/pages/database-detail-settings.tsx
Make this information more clear: **This action does not stop replication.**
> change-unlink-replica-text

- src/ui/pages/settings-profile.tsx
Add links to security page from the profile page
> Add links to security page from the profile page 

- src/app/test/app-detail-service-scale.test.tsx
- src/deploy/plan/index.ts
- src/mocks/data.ts
- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/app-detail-service-scale.tsx
Depends on:
- https://github.com/aptible/deploy-api/pull/1622
> Check activePlan for autoscaling

- .github/workflows/staging.yml
Add the key to allow Mintlify Chat to work in staging
> Add Mintlify Chat to Staging

- src/app/packages.ts
- src/bootup/index.ts
- src/modal/index.ts
- src/notice/index.ts
- src/schema/schema.ts
- src/types/index.ts
- src/types/modal.ts
- src/types/ux.ts
- src/ui/layouts/app-sidebar-layout.tsx
- src/ui/shared/index.ts
- src/ui/shared/modal-portal.tsx
- src/ui/shared/notice.tsx
> refactor: use banner instead of modal for backup rp notice

- src/api/index.ts
- src/bootup/index.ts
- src/deploy/operation/index.ts
- src/ui/hooks/use-latest-code-results.ts
- src/ui/hooks/use-paginate-operations.ts
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/shared/activity.tsx
Depends on:
- https://github.com/aptible/deploy-api/pull/1636
Main Activity page
subpages (App, Database, etc)
> Filter operations by status, type, and resource_type

- src/bootup/index.ts
- src/deploy/cost/calc.test.ts
- src/deploy/cost/calc.ts
- src/deploy/cost/index.ts
- src/deploy/entities.ts
- src/deploy/index.ts
- src/deploy/search/index.ts
- src/deploy/service/index.ts
- src/environment-table/index.ts
- src/schema/factory.ts
- src/schema/schema.ts
- src/stack-table/index.ts
- src/types/deploy.ts
- src/ui/layouts/environment-detail-layout.tsx
- src/ui/layouts/service-detail-layout.tsx
- src/ui/layouts/stack-detail-layout.tsx
- src/ui/pages/services.tsx
- src/ui/pages/stacks.tsx
- src/ui/shared/app/app-list.tsx
- src/ui/shared/app/services-detail.tsx
- src/ui/shared/db/database-list.tsx
- src/ui/shared/environment/environment-list.tsx
https://app.shortcut.com/aptible/story/29248/use-new-costs-api-in-the-ui?vc_group_by=day&ct_workflow=all&cf_workflow=500000186
> refactor: use cost estimates api

- src/ui/pages/plans.tsx
> Hide plan selector from legacy plan holders

- src/ui/pages/search.tsx
Change cursor pointer behavior for search results list
https://github.com/user-attachments/assets/53cb6e20-8a10-4c57-b359-5ea58cf9885e
> search-results-cursor-tweak

- src/ui/pages/create-env-app.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1736971292680989
> fix(db): prevent form submit from reloading page

- src/deploy/search/index.ts
https://app.shortcut.com/aptible/story/29205/update-sorting-to-group-autoscaling-statuses-together
> fix: scale recs sorting

- src/ui/pages/app-detail-service-scale.tsx
- src/ui/pages/database-detail-scale.tsx
- src/ui/shared/button.tsx
- src/ui/shared/scale-recs.tsx
> chore: more copy on container right-sizing recs

- src/ui/pages/app-create-endpoint.tsx
In response to https://aptible.zendesk.com/agent/tickets/56330
Adding a blurb about FORCE_SSL when creating an HTTP(S) endpoint.
> Add a force_ssl reference when creating HTTP(S) endpoints

- src/deploy/manual_scale_recommendation/index.ts
- src/schema/factory.ts
- src/types/state.ts
- src/ui/shared/scale-recs.tsx
Reference: https://github.com/aptible/deploy-api/pull/1674
Reference: https://app.shortcut.com/aptible/story/30400/update-the-ui-after-the-user-takes-a-scaling-rec-so-that-the-rec-is-no-longer-displayed
> chore: check if service size has changed since we made a recommendation

- src/bootup/index.ts
- src/ui/layouts/perm-required.tsx
Story details: https://app.shortcut.com/aptible/story/31180
> fix: [sc-31180] app-ui: restricted pages cannot be accessed directly via URL

- src/projects/index.ts
- src/ui/pages/app-deploy-configure.test.tsx
- src/ui/pages/app-deploy-configure.tsx
https://aptible.slack.com/archives/C05CMUW3LHX/p1738947239423319
> refactor(ftux): remove service def

- src/ui/shared/endpoint/util.tsx
A fix for the line breaking issues reported 3/15/2025 on internal issue 57110
> adjust endpoint URL line spacing for better readability

- src/schema/factory.ts
- src/types/deploy.ts
- src/ui/pages/settings-team-diagnostics-integrations-add.tsx
- src/ui/pages/settings-team-diagnostics-integrations-edit.tsx
- src/ui/pages/settings-team-diagnostics-integrations.tsx
Note: **updating** these integration configurations currently doesn't work, but that's due to a bug in deploy-api which I'll open a fix for separately.
> [sc-30939] [sc-30941] Add UI for configuring Datadog and PagerDuty integrations

- src/ui/pages/diagnostics-create.tsx
- src/ui/pages/diagnostics.tsx
- src/ui/shared/index.ts
- src/ui/shared/timezone-context.tsx
- src/ui/shared/timezone-toggle.tsx
- src/ui/shared/timezones.ts
If I told you I didn't write this, would you be surprised? Obviously I looked it over, but it's still worth a closer review because of that. 
This bridges the gap between my last TZ implementation (which I did with minimal feedback) and what ultimately ended up requested (via actual clear feedback).
> Allow for toggling tz between UTC and local
